/* Test Prep Hub — Reading and Writing question bank, batch 3.
   Adds Craft and Structure items that aren't words-in-context (text purpose, text structure,
   the function of a sentence, and cross-text connections), so practice matches the real mix.
   The correct answer is always listed first (a: 0); the app shuffles choices when shown. */
(function (root) {
  const BANK = root.RWBank || (typeof require !== "undefined" ? require("./rwbank.js") : []);
  const Q = (id, sk, lv, p, q, o, e, t) => ({ id, d: "cs", sk, lv, p, q, o, a: 0, e, t });
  const PURPOSE = "Which choice best states the main purpose of the text?";
  const STRUCT = "Which choice best describes the overall structure of the text?";
  const FUNC = "Which choice best describes the function of the underlined sentence in the text as a whole?";
  const TP = "Ask what the author is DOING (explaining, challenging, describing), not just what the topic is.";
  const TS = "Summarize each sentence in two or three words, then match the pattern.";
  const TF = "Ask how the sentence connects to the ones before and after it.";

  const MORE = [
    Q("ps01", "Text purpose", 1, "Honeybees that find a good patch of flowers return to the hive and perform a \"waggle dance.\" The angle of the dance relative to straight up tells other bees the direction of the flowers compared with the sun, and the length of each waggle run signals how far away the flowers are.",
      PURPOSE, ["To explain how honeybees communicate the location of food", "To argue that honeybees are more intelligent than other insects", "To describe the different kinds of flowers that honeybees prefer", "To compare the dances of honeybees with those of other animals"],
      "Every sentence explains how the dance shows direction and distance to food. The text doesn't argue or compare.", TP),
    Q("ps02", "Text purpose", 2, "Many people assume that a city's tallest buildings are always its newest. In Chicago, however, several towers completed in the 1920s and 1930s still rise above many office buildings constructed decades later, partly because some later projects were limited by zoning rules and changing demand for office space.",
      PURPOSE, ["To challenge a common assumption by presenting a counterexample", "To explain why zoning rules were created in Chicago", "To argue that older buildings are more attractive than newer ones", "To describe how tall buildings are designed to resist wind"],
      "The text opens with an assumption (\"Many people assume\") and then gives Chicago as a case that doesn't fit it.", "\"Many people assume… however\" usually signals a text that challenges an assumption."),
    Q("ps03", "Text structure", 2, "For years, astronomers classified Pluto as the ninth planet. Then, in the early 2000s, they discovered several other icy bodies of similar size in the same distant region of the solar system. Rather than add many new planets, the International Astronomical Union adopted a stricter definition of \"planet\" in 2006, one that Pluto did not meet.",
      STRUCT, ["It describes an earlier view, presents new findings, and then explains how the view changed in response", "It presents a scientific debate and then argues for one side of it", "It compares Pluto with each of the other planets in turn", "It describes a problem and then explains why it remains unsolved"],
      "Old view (Pluto is a planet) → new discovery (similar icy bodies) → change (new definition). That's the pattern in the first choice.", TS),
    Q("ps04", "Text structure", 3, "Economists have long debated why some neighborhood shops survive the arrival of large chain stores while others close. A common explanation is price: shops that can't match chain prices lose customers. A recent study of small hardware stores complicates this view. The stores that survived weren't the cheapest; they were the ones whose staff offered detailed advice that the chains' employees rarely gave.",
      STRUCT, ["It introduces a question, presents a common answer, and then describes research that suggests the answer is incomplete", "It presents a theory and then provides several studies that confirm it", "It describes a trend and then predicts how it will continue", "It compares two economists' views and concludes that both are wrong"],
      "Question (why do some shops survive?) → common answer (price) → study that \"complicates this view\" (advice mattered).", TS),
    Q("ps05", "Text structure", 2, "The following text is adapted from a short story.\nMarisol had practiced the piano piece every afternoon for a month. <u>On the night of the recital, her hands trembled so much that she almost left the stage.</u> Then she heard the first notes under her own fingers, steady and clear, and the fear slipped away.",
      FUNC, ["It introduces a moment of doubt that the final sentence resolves", "It explains why Marisol chose to learn the piano", "It describes the audience's reaction to Marisol's performance", "It shows that Marisol had not practiced enough"],
      "The trembling hands create tension; the last sentence (\"the fear slipped away\") resolves it. The first sentence says she practiced every day, so the last choice contradicts the text.", TF),
    Q("ps06", "Text structure", 3, "Some historians have portrayed the medieval period in Europe as an age with little scientific activity. <u>Yet scholars in this period built mechanical clocks, improved eyeglasses, and translated and expanded on earlier works of mathematics and astronomy.</u> These achievements suggest that the period's reputation owes more to later writers' assumptions than to the historical record.",
      FUNC, ["It offers evidence that challenges the view described in the first sentence", "It explains why later writers disliked the medieval period", "It introduces the main claim that the rest of the text supports", "It describes a limitation of medieval scientific methods"],
      "\"Yet\" signals a contrast: the sentence lists achievements that push back against \"little scientific activity.\" The main claim comes in the last sentence, not this one.", TF),
    Q("ps07", "Text purpose", 3, "The following text is adapted from a 19th-century essay.\nWe praise the traveler who crosses oceans to see famous wonders, yet we seldom praise the person who notices the changing light on a familiar street. The second kind of seeing is harder, for it asks us to find something new in what habit has made invisible.",
      PURPOSE, ["To suggest that paying close attention to familiar surroundings is a valuable skill", "To criticize people who travel to see famous places", "To describe the appearance of a street at different times of day", "To argue that ocean travel was dangerous in the 19th century"],
      "The author values \"the second kind of seeing\" (noticing the familiar) and calls it harder. It doesn't attack travelers; it says we \"seldom praise\" the other kind.", "Watch for extreme choices like \"criticize.\" The author's tone is gentler."),
    Q("xc01", "Cross-text connections", 2, "Text 1\nSome teachers argue that students should write first drafts by hand. They point to studies in which students who took notes by hand remembered lectures better than students who typed their notes.\n\nText 2\nThe benefit of handwriting in those studies came mainly from the way it forced students to summarize rather than copy word for word. Students who were taught to summarize while typing remembered just as much as those who wrote by hand.",
      "Based on the texts, how would the author of Text 2 most likely respond to the teachers in Text 1?", ["By suggesting that the benefit they describe may come from summarizing rather than from handwriting itself", "By agreeing that students should never use computers in class", "By claiming that typed notes are always more accurate than handwritten ones", "By arguing that students remember lectures better when they don't take notes"],
      "Text 2 says the real cause was summarizing, and typists who summarized did just as well. That undercuts handwriting as the cause.", "Cross-text: find what Text 2 says is the REAL cause or the missing piece."),
    Q("xc02", "Cross-text connections", 3, "Text 1\nArchaeologists once believed that the large stone statues on Rapa Nui (Easter Island) were moved by rolling them on wooden logs, and that cutting trees for this purpose helped cause the island's deforestation.\n\nText 2\nIn experiments, researchers found that a team of people using ropes could \"walk\" a replica statue upright by rocking it from side to side, a method that requires no logs. Oral traditions on the island also describe the statues as having walked.",
      "Based on the texts, the researchers in Text 2 would most likely respond to the belief in Text 1 by", ["pointing out that the statues could have been moved without the logs the belief depends on", "agreeing that log rolling was the only practical way to move the statues", "arguing that the statues were carved in the places where they now stand", "claiming that the island was never forested"],
      "Text 1's explanation needs logs. Text 2 shows a method that \"requires no logs,\" which weakens that part of the belief. It doesn't claim anything about whether the island had forests.", "The right answer targets the specific link in Text 1 that Text 2 undercuts."),
    Q("xc03", "Cross-text connections", 2, "Text 1\nUrban planner Keiko Arai argues that adding protected bike lanes makes streets safer for everyone, because drivers slow down when lanes are narrower and cyclists no longer weave through traffic.\n\nText 2\nA review of several cities that added protected bike lanes found that injuries to cyclists fell sharply. The reviewers note, though, that results for pedestrians varied and depended heavily on how intersections were designed.",
      "Based on the texts, how would the reviewers in Text 2 most likely respond to Arai's claim in Text 1?", ["By agreeing that the lanes improve cyclist safety but cautioning that the benefit to everyone may depend on other design choices", "By rejecting the claim that bike lanes affect cyclist safety", "By arguing that bike lanes should be removed from intersections", "By claiming that drivers speed up when lanes become narrower"],
      "Text 2 supports part of Arai's claim (cyclist injuries fell) but qualifies \"safer for everyone\": pedestrian results varied.", "Look for \"partly agrees, partly questions\" answers. Text 2 often does both."),
    Q("xc04", "Cross-text connections", 3, "Text 1\nMany nutrition guides treat the \"eight glasses of water a day\" rule as settled science, advising people to drink that amount no matter what else they consume.\n\nText 2\nPhysiologists point out that much of the water people need comes from food and from other drinks, and that healthy people's thirst is generally a reliable guide. The eight-glass figure, they note, has no clear origin in controlled research.",
      "Based on the texts, the physiologists in Text 2 would most likely say that the guides described in Text 1", ["present a rule as more certain than the evidence justifies", "correctly identify the amount of water every person needs", "underestimate the amount of water that people get from food", "rely too heavily on people's sense of thirst"],
      "Text 1 says the guides treat the rule as \"settled science\"; Text 2 says it has \"no clear origin in controlled research.\" So the guides overstate its certainty.", "Match Text 2's key phrase (\"no clear origin\") to what Text 1 claims (\"settled science\")."),
    Q("xc05", "Cross-text connections", 2, "Text 1\nWhen the first public libraries opened in many American towns, supporters argued that they would give working people access to books they could not otherwise afford.\n\nText 2\nRecords from several early public libraries show that many of their most frequent borrowers were factory workers, clerks, and apprentices. Novels and practical manuals on trades were among the most popular books.",
      "Based on the texts, how does the information in Text 2 relate to the argument in Text 1?", ["It suggests that the libraries served the readers their supporters hoped they would", "It shows that the libraries' supporters misunderstood what people wanted to read", "It explains why public libraries were expensive to build", "It argues that working people preferred to buy their own books"],
      "Text 1's hope was access for working people; Text 2's records show workers were frequent borrowers. The evidence fits the argument.", "Not every Text 2 disagrees. Sometimes it supports Text 1 with evidence.")
  ];
  for (const q of MORE) BANK.push(q);
  root.RWBank = BANK;
  if (typeof module !== "undefined") module.exports = BANK;
})(typeof window !== "undefined" ? window : globalThis);
