/* Test Prep Hub — strategy cards.
   One short, memorable rule per question type, with how to recognize it (spot), the steps (solve),
   the Desmos shortcut for math (desmos), and the most common wrong-answer pattern (trap).
   strategyFor(q) maps any question to its card. */
(function (root) {
  const S = {
    /* ---------- Standard English Conventions ---------- */
    boundaries: { name: "Semicolon = period", area: "Grammar",
      spot: "The blank sits between two groups of words, and the choices change the punctuation.",
      rule: "Two complete sentences need a period or a semicolon, or a comma plus and/but/so. A comma alone is never enough.",
      steps: ["Read each side of the blank on its own.", "If both could stand alone as sentences, pick a period or semicolon.", "If one side can't stand alone, don't use a semicolon."],
      trap: "The comma splice: a lone comma between two full sentences looks natural but is wrong." },
    conjadv: { name: "; however,", area: "Grammar",
      spot: "A word like however, therefore, moreover, or for example sits between two complete sentences.",
      rule: "Those words can't join sentences. Use a semicolon (or period) before them and a comma after them.",
      steps: ["Check that both sides are complete sentences.", "Put the semicolon before the linking word.", "Put a comma right after it."],
      trap: "\", however,\" between two full sentences. It feels right because we pause there when speaking." },
    extra: { name: "Commas come in pairs", area: "Grammar",
      spot: "A describing phrase has been dropped into the middle of a sentence.",
      rule: "Extra information is fenced off on both sides with the same mark: two commas or two dashes.",
      steps: ["Find where the extra information starts.", "Match its opening mark (comma or dash).", "Read the sentence without the extra part: it should still work."],
      trap: "Mixing marks (a dash to open, a comma to close), or closing with a semicolon." },
    agreement: { name: "Cross out the middle", area: "Grammar",
      spot: "The choices are different forms of the same verb (is/are, has/have).",
      rule: "Cross out everything between the subject and the verb, then match singular to singular and plural to plural.",
      steps: ["Find the verb's real subject (usually the first noun).", "Cross out 'of…', 'in…', 'from…' phrases in between.", "Match the verb to that subject and keep the tense."],
      trap: "Matching the verb to the nearest noun instead of the real subject." },
    possessive: { name: "Owner, then apostrophe", area: "Grammar",
      spot: "The choices differ only in apostrophes and s's.",
      rule: "One owner: add 's. Several owners ending in s: add just an apostrophe. Nothing owned: no apostrophe.",
      steps: ["Ask: does this word own the next noun?", "Count the owners: one or more than one?", "One → 's. More than one (ending in s) → s'."],
      trap: "Using 's for a plural owner, or adding an apostrophe to a plain plural." },
    pronoun: { name: "Point the pronoun", area: "Grammar",
      spot: "The choices are pronouns (it, they, its, their, this).",
      rule: "Point to the exact noun the pronoun replaces, then match its number. 'Its' owns; 'it's' means 'it is.'",
      steps: ["Find the noun the pronoun stands for.", "Singular noun → it/its. Plural → they/their/them.", "Check its vs. it's by expanding to 'it is.'"],
      trap: "Using 'their' for a single company, team, or group." },
    modifier: { name: "Who's doing it?", area: "Grammar",
      spot: "The sentence opens with a describing phrase and a comma, and the choices start with different nouns.",
      rule: "The noun right after the comma must be the one doing the action in the opening phrase.",
      steps: ["Ask who or what did the opening action.", "Pick the choice that puts that noun first."],
      trap: "A choice that starts with 'the results' or 'the data' when a person did the action." },
    tense: { name: "Match the timeline", area: "Grammar",
      spot: "The choices are the same verb in different tenses or forms.",
      rule: "Let the time clues (dates, 'by the time', other verbs) set the tense. 'Had' shows the earlier of two past events.",
      steps: ["Underline the time clues.", "Match the other verbs in the sentence.", "Use 'had' + verb only for something finished before another past event."],
      trap: "Switching tense mid-sentence because a choice 'sounds' smoother." },
    punctuation: { name: "Colon = here it comes", area: "Grammar",
      spot: "The choices differ by colon, semicolon, or comma before a list or explanation.",
      rule: "A colon follows a complete sentence and introduces a list or explanation. No comma between a subject and its verb.",
      steps: ["Is the part before the mark a complete sentence? Then a colon can introduce what follows.", "Lists inside lists? Separate the big items with semicolons.", "Never split a subject from its verb with a comma."],
      trap: "A colon after an incomplete sentence (e.g., 'The ingredients are: …')." },
    /* ---------- Expression of Ideas ---------- */
    transitions: { name: "Name the relationship first", area: "Writing",
      spot: "The blank starts the second sentence and the choices are linking words.",
      rule: "Before looking at the choices, label the link: contrast, result, addition, example, or similarity.",
      steps: ["Cover the choices.", "Say how sentence 2 relates to sentence 1 in one word.", "Pick the choice with that meaning. Two choices mean the same thing? Neither is the answer."],
      trap: "Picking a word that sounds formal ('Moreover') when the ideas actually contrast." },
    synthesis: { name: "Goal words only", area: "Writing",
      spot: "Bulleted student notes, then 'The student wants to…'",
      rule: "Ignore the notes at first. Read the goal, then pick the choice that does exactly that and nothing else.",
      steps: ["Underline the goal's key words (compare, explain why, emphasize, introduce).", "Eliminate choices that are true but don't do the goal.", "Compare/contrast goals need both things mentioned."],
      trap: "The most detailed or impressive-sounding choice that ignores the goal." },
    /* ---------- Craft and Structure ---------- */
    wic: { name: "Predict, then match", area: "Reading",
      spot: "A blank in the text (or a quoted word) and four vocabulary choices.",
      rule: "Cover the choices, find the clue in the sentence, say your own word, then pick the closest match.",
      steps: ["Find the clue: a colon, 'although', 'rather than', or an example.", "Put your own simple word in the blank.", "Choose the option closest to your word. Watch for 'not' and 'less'."],
      trap: "A fancy word that's related to the topic but doesn't fit the clue." },
    purpose: { name: "What is the text DOING?", area: "Reading",
      spot: "Asks for the main purpose, the overall structure, or the function of a sentence.",
      rule: "Answer with a verb: challenge, explain, compare, describe, argue. Then check that every part of the choice happens in the text.",
      steps: ["Summarize the text in one short sentence with a verb.", "Watch for turns: 'However', 'Yet', 'In fact'.", "Eliminate choices that are too narrow (one detail) or too broad."],
      trap: "A choice that describes one sentence, or claims the author argues when they only describe." },
    crosstext: { name: "Agree, then dispute", area: "Reading",
      spot: "Text 1 and Text 2, and a question about how one author would respond.",
      rule: "Find exactly what Text 2 accepts from Text 1 and exactly what it pushes back on.",
      steps: ["Summarize Text 1's claim.", "Find Text 2's reaction: agrees, disagrees, or adds a condition.", "Pick the choice that matches that reaction, not an extreme version."],
      trap: "An extreme choice (Text 2 'rejects everything') when Text 2 only qualifies the claim." },
    /* ---------- Information and Ideas ---------- */
    central: { name: "Whole passage, not one detail", area: "Reading",
      spot: "Asks for the main idea or best summary.",
      rule: "The main idea covers every sentence. A choice that fits only one line is a detail.",
      steps: ["State the main point in your own words.", "Check each choice against the whole text.", "Eliminate choices that are too narrow or add ideas the text doesn't say."],
      trap: "A true detail from the passage that isn't the main point." },
    inference: { name: "Most cautious claim", area: "Reading",
      spot: "The text ends with a blank, and the question asks what most logically completes it.",
      rule: "Pick the choice that the text fully supports with no extra assumptions: usually the most modest one.",
      steps: ["Find what the text rules out and what it leaves.", "Predict the conclusion.", "Eliminate choices with extreme words (always, never, proves) or new ideas."],
      trap: "An exciting conclusion that goes further than the evidence." },
    evidence: { name: "Same subject, same outcome", area: "Reading",
      spot: "A claim, then 'Which finding/quotation would most directly support (or weaken) it?'",
      rule: "Support must match the claim's exact subject and outcome. To weaken, look for another explanation.",
      steps: ["Break the claim into subject + outcome.", "Pick the choice that shows that exact outcome for that subject.", "Weaken questions: find the choice that gives a different cause."],
      trap: "A choice about the right topic that doesn't show the specific outcome." },
    quant: { name: "Claim first, then table", area: "Reading",
      spot: "A table or graph with a claim, and choices that quote numbers.",
      rule: "Read the claim, not the table, first. Then check each choice against the table and the claim.",
      steps: ["Underline every part of the claim.", "Cross out choices that misread the table.", "Of the true choices, pick the one that supports every part of the claim."],
      trap: "A choice with correct numbers that supports a different point." },
    /* ---------- Algebra ---------- */
    lineq: { name: "Undo in reverse", area: "Math",
      spot: "One equation with one variable.",
      rule: "Undo operations in reverse order: add or subtract first, then divide. Check by plugging back in.",
      steps: ["Distribute and collect x-terms on one side.", "Move the constants to the other side.", "Divide, then plug your answer back in."],
      desmos: "Type the left side as y1 and the right side as y2; the x-value where they cross is the answer.",
      trap: "Sign errors when moving a negative number across the equals sign." },
    scaled: { name: "Look for the multiple", area: "Math",
      spot: "They give one expression's value and ask for a related expression.",
      rule: "Don't solve for x if you don't have to: the new expression is often a multiple of the old one.",
      steps: ["Compare the two expressions.", "Multiply the known value by the same factor.", "Adjust any added constant."],
      trap: "Stopping at x and giving x as the answer." },
    systems: { name: "Graph both, click the crossing", area: "Math",
      spot: "Two equations with x and y.",
      rule: "Add or subtract the equations to cancel a variable, or graph both and read the intersection.",
      steps: ["Line up x, y, and constants.", "Multiply one equation so a variable cancels, then add.", "Solve, then substitute back for the other variable."],
      desmos: "Enter both equations and click where the lines cross.",
      trap: "Answering with x when they asked for y (or x + y)." },
    slope: { name: "Rise over run", area: "Math",
      spot: "Two points, a graph, or a line's equation.",
      rule: "Slope = (change in y) ÷ (change in x). Parallel = same slope; perpendicular = flip and change the sign.",
      steps: ["Subtract the y's, subtract the x's in the same order.", "Find the intercept by plugging in one point.", "Plug both points into the answer to check."],
      desmos: "Enter the two points as a table; add y = mx + b with sliders or type the regression y1 ~ mx1 + b.",
      trap: "Flipping to run over rise, or mixing the order of the points." },
    model: { name: "Rate × variable + start", area: "Math",
      spot: "A real-world equation like C = 25 + 8h.",
      rule: "The number multiplied by the variable is the rate (per one unit). The constant is the starting value.",
      steps: ["Find the number attached to the variable: that's per unit.", "The number standing alone is the value when the variable is 0.", "To find an input, set the equation equal to the total and solve."],
      trap: "Calling the starting fee the rate, or vice versa." },
    inequality: { name: "At most ≤, at least ≥", area: "Math",
      spot: "Words like at most, at least, no more than, minimum, maximum.",
      rule: "Translate the words, solve, then round the way the story needs: down for 'at most', up for 'at least'.",
      steps: ["Write the inequality: fixed amount + rate × number vs. limit.", "Solve like an equation.", "Round to a whole number in the right direction."],
      trap: "Rounding 7.8 classes up to 8 when you can't go over the budget." },
    nosolution: { name: "Same slope = parallel", area: "Math",
      spot: "A system with a constant and 'no solution' or 'infinitely many solutions.'",
      rule: "No solution: same slope, different intercept. Infinitely many: the same line.",
      steps: ["Write both in the same form.", "Set the x- and y-coefficients in the same ratio.", "Check the constants: different → no solution; same ratio → infinitely many."],
      trap: "Making the lines identical when the question asks for no solution." },
    linfunc: { name: "Two points → slope → line", area: "Math",
      spot: "f(a) and f(b) are given for a linear function.",
      rule: "Treat each f(x) value as a point, find the slope, then write the line.",
      steps: ["Points: (a, f(a)) and (b, f(b)).", "Slope = difference in outputs ÷ difference in inputs.", "Find b, then evaluate."],
      desmos: "Type the two points in a table and fit y1 ~ mx1 + b; then evaluate.",
      trap: "Averaging the two outputs instead of using the slope." },
    /* ---------- Advanced Math ---------- */
    quadratic: { name: "Factor or graph", area: "Math",
      spot: "A quadratic equation set equal to 0.",
      rule: "Find two numbers that multiply to c and add to b, or graph and read the x-intercepts. Sum of roots = −b/a, product = c/a.",
      steps: ["Divide out any common factor.", "Factor, or use the quadratic formula.", "Answer exactly what's asked: the roots, their sum, or their product."],
      desmos: "Graph the quadratic and click the x-intercepts.",
      trap: "Sign flips: (x − 7) gives x = 7, not −7." },
    evaluate: { name: "Parenthesize negatives", area: "Math",
      spot: "f(x) is given and you need f(a number).",
      rule: "Replace every x with the number in parentheses. A negative squared is positive.",
      steps: ["Write the function with (number) in place of x.", "Do exponents first, then multiply, then add.", "Double-check any negative signs."],
      desmos: "Type f(x) = … then f(−2) on the next line.",
      trap: "Writing −2² = −4 instead of (−2)² = 4." },
    exponential: { name: "Start × factor^(time/period)", area: "Math",
      spot: "Doubles, triples, grows or decays by a percent.",
      rule: "Growth factor above 1 = growth, below 1 = decay. The percent is the distance from 1. The exponent counts how many periods have passed.",
      steps: ["Start value in front.", "Factor: 2 for doubling, 1 + r for growth, 1 − r for decay.", "Exponent: time ÷ length of one period."],
      trap: "Reading 0.88 as an 88% decrease (it's a 12% decrease)." },
    equivalent: { name: "Expand, or graph both", area: "Math",
      spot: "'Which expression is equivalent to…'",
      rule: "Multiply out carefully, or graph the original and each choice: equivalent expressions draw the same curve.",
      steps: ["Multiply every term by every term.", "Combine like terms.", "Plug in x = 2 to spot-check your choice."],
      desmos: "Graph the original and each choice; the matching curve is the answer.",
      trap: "(x + a)² ≠ x² + a². Don't forget the middle term 2ax." },
    vertex: { name: "Vertex form reads the answer", area: "Math",
      spot: "A parabola's minimum, maximum, or vertex.",
      rule: "In y = a(x − h)² + k, the vertex is (h, k). a > 0 opens up (minimum); a < 0 opens down (maximum). Otherwise x = −b/(2a).",
      steps: ["Rewrite in vertex form or use x = −b/(2a).", "Plug that x in to get the y-value.", "Check the direction the parabola opens."],
      desmos: "Graph it and click the turning point.",
      trap: "The sign flip: (x + 3)² means h = −3." },
    discriminant: { name: "b² − 4ac counts roots", area: "Math",
      spot: "'How many real solutions?'",
      rule: "Positive: two solutions. Zero: one. Negative: none.",
      steps: ["Write the equation as ax² + bx + c = 0.", "Compute b² − 4ac.", "Read its sign."],
      desmos: "Graph it and count how many times it touches the x-axis.",
      trap: "Forgetting to move everything to one side before reading a, b, c." },
    exponents: { name: "Multiply add, divide subtract, power multiply", area: "Math",
      spot: "Powers of the same base combined.",
      rule: "Multiply → add exponents. Divide → subtract. Power of a power → multiply.",
      steps: ["Handle powers of powers first.", "Then add or subtract for multiplying or dividing.", "Check with a small number like x = 2."],
      trap: "Multiplying exponents when you should add them." },
    radical: { name: "Square both sides, then check", area: "Math",
      spot: "A square root equal to a number.",
      rule: "Square both sides to remove the root, solve, and plug back in to reject extra answers.",
      steps: ["Isolate the square root.", "Square both sides.", "Solve and check in the original."],
      trap: "Squaring only one side, or skipping the check." },
    graphs: { name: "Read the graph's key points", area: "Math",
      spot: "A line or parabola is drawn and you must match an equation or a value.",
      rule: "Use the easiest points: the y-intercept, a clean grid point, or the vertex.",
      steps: ["Read the y-intercept.", "Count rise and run between two grid points (or read the vertex).", "Eliminate choices that don't match those points."],
      trap: "Misreading the scale or counting squares in the wrong direction." },
    nonlinear: { name: "Set them equal", area: "Math",
      spot: "A line and a parabola, or 'where do the graphs intersect?'",
      rule: "Set the two right sides equal, move everything to one side, and solve the quadratic.",
      steps: ["y = y: write one equation.", "Rearrange to 0 = ax² + bx + c and factor.", "Substitute x back if they ask for y."],
      desmos: "Graph both and click each intersection point.",
      trap: "Giving x-values when they asked for y (or the sum of y's)." },
    /* ---------- Problem-Solving & Data Analysis ---------- */
    percent: { name: "Multiply by the factor", area: "Math",
      spot: "Discounts, tax, percent increase or decrease.",
      rule: "Percent change = change ÷ original. For discounts and tax, multiply by (1 − rate) or (1 + rate), one step at a time.",
      steps: ["Find the original (starting) amount.", "Use a multiplier for each change in order.", "Successive changes multiply; never add the percents."],
      trap: "Dividing by the new amount, or adding a 20% rise and a 20% fall to get 0%." },
    mean: { name: "Totals, not averages", area: "Math",
      spot: "A mean or average with a missing value.",
      rule: "Total = mean × count. Work with totals, then subtract.",
      steps: ["Target total = target mean × number of values.", "Add the known values.", "Missing value = target total − known total."],
      trap: "Averaging the averages." },
    median: { name: "Sort first", area: "Math",
      spot: "Median of a list or a chart.",
      rule: "Put the values in order. Middle value; with an even count, average the two middle values.",
      steps: ["Sort from least to greatest.", "Find the middle position.", "Average the two middle values if needed."],
      trap: "Taking the middle of the unsorted list." },
    rates: { name: "Units ride along", area: "Math",
      spot: "Speed, rates, and unit conversions.",
      rule: "Write units next to every number; they tell you when to multiply, divide, or convert.",
      steps: ["Find the unit rate (per 1).", "Multiply by the new amount.", "Convert hours ↔ minutes at the end if needed."],
      trap: "Answering in hours when they asked for minutes." },
    probability: { name: "The 'given' group is the bottom", area: "Math",
      spot: "A two-way table and 'if a … is chosen at random'.",
      rule: "The group named after 'if a…' is the denominator. The part you want is the numerator.",
      steps: ["Circle the group after 'if a … is chosen'.", "Use that row or column total as the denominator.", "Find the count that fits both conditions."],
      trap: "Dividing by the grand total instead of the group's total." },
    ratio: { name: "Add the parts", area: "Math",
      spot: "A ratio and a total.",
      rule: "Add the ratio parts, divide the total by that sum, then multiply by the part you need.",
      steps: ["Total parts = sum of the ratio numbers.", "One part = total ÷ total parts.", "Answer = your share × one part."],
      trap: "Dividing the total by one side of the ratio." },
    scatter: { name: "Use the line, not the dots", area: "Math",
      spot: "A scatterplot with a line of best fit.",
      rule: "Predictions come from the line's equation. Slope = average change per 1 unit of x.",
      steps: ["Plug the x-value into the line of best fit.", "Interpret slope as 'about … per 1 …'.", "Counting dots? Compare each dot to the line right above or below it."],
      trap: "Reading the value of the nearest dot instead of the line." },
    datadisplay: { name: "Values vs. counts", area: "Math",
      spot: "A bar chart or frequency table.",
      rule: "The bars are counts; the labels are the values. Median and mean are about the values.",
      steps: ["List how many times each value appears.", "For the median, count to the middle position.", "For the mean, sum value × count, then divide by the total count."],
      trap: "Reporting a bar height as the median." },
    sampling: { name: "Random sample, range answer", area: "Math",
      spot: "A survey, a margin of error, or 'can the results be generalized?'",
      rule: "Estimate ± margin of error gives a plausible range. Only random samples generalize to the whole group. Bigger samples mean smaller margins.",
      steps: ["Find the plausible range: estimate − MOE to estimate + MOE.", "Check how the sample was chosen.", "Avoid choices that claim an exact value or cause and effect."],
      trap: "Treating the sample percent as exact for everyone." },
    /* ---------- Geometry & Trigonometry ---------- */
    pythag: { name: "Know the triples", area: "Math",
      spot: "A right triangle with two sides given.",
      rule: "a² + b² = c². Spot 3-4-5, 5-12-13, 8-15-17 and their multiples to skip the arithmetic.",
      steps: ["Is the missing side the hypotenuse (longest)?", "Check for a triple.", "Otherwise square, add or subtract, then take the square root."],
      trap: "Adding when the missing side is a leg (you subtract)." },
    trig: { name: "SOH-CAH-TOA", area: "Math",
      spot: "sin, cos, or tan in a right triangle.",
      rule: "Sine = Opposite/Hypotenuse, Cosine = Adjacent/Hypotenuse, Tangent = Opposite/Adjacent. sin A = cos B when A + B = 90°.",
      steps: ["Stand at the angle they name.", "Label opposite, adjacent, hypotenuse from there.", "Build the ratio; find a missing side with a triple."],
      trap: "Labeling sides from the wrong angle." },
    circle: { name: "(x − h)² + (y − k)² = r²", area: "Math",
      spot: "A circle's equation, center, or radius.",
      rule: "Center (h, k) has flipped signs; the number on the right is r². Messy form? Complete the square.",
      steps: ["Group x's and y's.", "Complete the square: add (half the coefficient)² to both sides.", "Read the center and take √ for the radius."],
      desmos: "Graph the equation and read the center and radius from the circle.",
      trap: "Forgetting the square root: the radius is √49 = 7, not 49." },
    angles: { name: "180 on a line, 90 in a corner", area: "Math",
      spot: "Supplementary, complementary, or triangle angles.",
      rule: "Straight line or triangle: 180°. Complementary: 90°. An exterior angle equals the two far interior angles added.",
      steps: ["Write the sum equation.", "Solve for the variable.", "Answer the angle they asked for (smaller or larger)."],
      trap: "Stopping at x when they asked for the other angle." },
    volume: { name: "Open the reference sheet", area: "Math",
      spot: "Volume or area of a solid.",
      rule: "Every formula you need is on the reference sheet. Plug in carefully and leave π in the answer if the choices do.",
      steps: ["Find the formula.", "Square or cube the radius first.", "Multiply by the other dimensions and any fraction (⅓, 4/3)."],
      trap: "Using the diameter instead of the radius." },
    similar: { name: "k, k², k³", area: "Math",
      spot: "Similar triangles or scaled figures.",
      rule: "Lengths scale by k, areas by k², volumes by k³.",
      steps: ["Find k from a matching pair of sides.", "Multiply the length you need by k.", "For area use k², for volume k³."],
      trap: "Scaling an area by k instead of k²." },
    arc: { name: "Fraction of the circle", area: "Math",
      spot: "Arc length or sector area with a central angle.",
      rule: "Part = (angle ÷ 360°) × whole. In radians, arc length = r × θ.",
      steps: ["Write the fraction angle/360.", "Multiply by 2πr (arc) or πr² (sector).", "Radians? Use s = rθ."],
      trap: "Using the area formula for an arc length." },
    radians: { name: "180° = π", area: "Math",
      spot: "Converting between degrees and radians.",
      rule: "Degrees → radians: × π/180. Radians → degrees: replace π with 180°.",
      steps: ["Write the conversion factor.", "Simplify the fraction.", "Check: 90° = π/2, 60° = π/3, 45° = π/4."],
      trap: "Multiplying by 180/π in the wrong direction." },
    special: { name: "x, x√3, 2x and x, x, x√2", area: "Math",
      spot: "30°-60°-90° or 45°-45°-90° triangles.",
      rule: "30-60-90: short leg x, long leg x√3, hypotenuse 2x. 45-45-90: legs x, hypotenuse x√2.",
      steps: ["Identify the triangle type.", "Find x from the side you know.", "Build the side you need."],
      trap: "Putting √3 on the side opposite the 30° angle." },
    literal: { name: "Treat letters like numbers", area: "Math",
      spot: "\"Which equation expresses h in terms of…\" or a formula with one unknown.",
      rule: "Undo the operations around the target letter in reverse order. If it appears twice, gather both terms and factor it out.",
      steps: ["Circle the letter you're solving for.", "Clear fractions, then add or subtract terms away from it.", "Divide last. Twice? Factor it out first."],
      desmos: "Pick numbers for the other letters, compute the answer, then test each choice with the same numbers.",
      trap: "Dividing only one term of a sum, or forgetting the ½ in the formula." },
    sysineq: { name: "Test both, fail one = out", area: "Math",
      spot: "Two inequalities and \"which point is a solution\".",
      rule: "A solution must make BOTH inequalities true. Points on a < or > line don't count; points on a ≤ or ≥ line do.",
      steps: ["Plug the point into the first inequality.", "If it passes, plug it into the second.", "Watch the boundary: is it strict (<, >) or not (≤, ≥)?"],
      desmos: "Type both inequalities. The answer is in the overlap of the two shaded regions.",
      trap: "A point exactly on a dashed (strict) boundary line." },
    polyops: { name: "Distribute every sign", area: "Math",
      spot: "Add, subtract, or multiply polynomials; \"true for all x\".",
      rule: "Subtracting flips every sign in the second polynomial. Multiplying: every term times every term. \"For all x\" means match coefficients.",
      steps: ["Rewrite with parentheses removed, signs distributed.", "Combine like terms (x² with x², x with x).", "For \"all x\": set matching coefficients equal and solve."],
      desmos: "Graph the original and a choice. If the graphs overlap exactly, they're equivalent.",
      trap: "Only flipping the sign of the first term when subtracting." },
    rational: { name: "Cross-multiply, then check", area: "Math",
      spot: "Fractions with x in the denominator.",
      rule: "Clear the fractions (cross-multiply or multiply by the common denominator). Then reject any answer that makes a denominator 0.",
      steps: ["Cross-multiply or multiply through.", "Expand carefully; x² terms often cancel.", "Check the answer in the original denominators."],
      desmos: "Graph both sides as y = … and click the intersection.",
      trap: "Cancelling single terms (x + 3)/x ≠ 3; only whole factors cancel." },
    spread: { name: "Spread = how far from the center", area: "Math",
      spot: "Range, standard deviation, or \"what happens if a value is removed\".",
      rule: "Range = max − min. Standard deviation = typical distance from the mean: bigger when values are spread out. Outliers move the mean and spread; the median barely moves.",
      steps: ["Sort the values.", "Compare spreads by eye; don't compute standard deviation.", "Outlier removed? Mean moves toward the rest; SD and range shrink."],
      trap: "Thinking the median moves as much as the mean when an outlier changes." },
    area: { name: "Percent changes multiply", area: "Math",
      spot: "Area or perimeter, or dimensions scaled or changed by a percent.",
      rule: "Area = length × width, so changes multiply: ×1.2 and ×0.8 give ×0.96 (a 4% decrease). Scaling lengths by k scales area by k².",
      steps: ["Turn each change into a multiplier (1 + p or 1 − p).", "Multiply the multipliers.", "Or test with a 10 by 10 rectangle."],
      trap: "Adding percents: +20% and −20% is NOT \"no change\"." },
    polygons: { name: "Parallel = equal or 180", area: "Math",
      spot: "Parallel lines and a transversal, exterior angles, or regular polygons.",
      rule: "Parallel lines make angles that are equal or add to 180°. Exterior angle = sum of the two far interior angles. A polygon's exterior angles total 360°.",
      steps: ["Decide: equal or supplementary?", "Write the equation and solve for x.", "Polygon? Interior sum = (n − 2) × 180°, each exterior = 360° ÷ n."],
      trap: "Stopping at x instead of finding the angle." },
    composition: { name: "Inside out", area: "Math",
      spot: "f(g(x)), or one function inside another.",
      rule: "Evaluate the inner function first, then feed that number into the outer function.",
      steps: ["Find the innermost value.", "Substitute it into the next function.", "Keep negatives in parentheses when squaring."],
      desmos: "Define f(x) and g(x), then type f(g(2)).",
      trap: "Doing the outer function first, which gives g(f(x)) instead." },
    perpendicular: { name: "Flip and switch", area: "Math",
      spot: "Parallel or perpendicular lines.",
      rule: "Parallel lines have the same slope. Perpendicular slopes are negative reciprocals: 2/3 becomes −3/2.",
      steps: ["Find the slope of the given line.", "Flip it and change the sign.", "Use the point in y = mx + b to find b."],
      trap: "Flipping without changing the sign (or the reverse)." },
    twoway: { name: "\"Given\" picks the denominator", area: "Math",
      spot: "A two-way table and \"given that\" or \"of those who…\".",
      rule: "The group after \"given that\" is the whole denominator: that row or column total only.",
      steps: ["Find the \"given\" row or column total.", "Find the cell in both groups.", "Divide cell ÷ that total."],
      trap: "Dividing by the grand total of the whole table." },
    general: { name: "Read the last line twice", area: "Strategy",
      spot: "Any question.",
      rule: "Before choosing, reread exactly what the question asks for.",
      steps: ["Underline what's being asked.", "Eliminate clearly wrong choices.", "Never leave a blank: wrong answers cost nothing."],
      trap: "Answering a different question than the one asked." }
  };

  const BY_GEN = {
    sec_boundary: "boundaries", sec_conjadv: "conjadv", sec_extra: "extra", sec_agree: "agreement", sec_poss: "possessive",
    eoi_trans: "transitions", ii_quant: "quant",
    alg_lineq: "lineq", alg_scaled: "scaled", alg_system: "systems", alg_slope: "slope", alg_model: "model", alg_ineq: "inequality", alg_nosol: "nosolution", alg_fx: "linfunc", alg_graphline: "graphs",
    adv_roots: "quadratic", adv_eval: "evaluate", adv_exp: "exponential", adv_equiv: "equivalent", adv_vertex: "vertex", adv_disc: "discriminant", adv_exprules: "exponents", adv_radical: "radical", adv_graph: "graphs", adv_linquad: "nonlinear",
    psda_discount: "percent", psda_pctchange: "percent", psda_mean: "mean", psda_median: "median", psda_rate: "rates", psda_prob: "probability", psda_ratio: "ratio", psda_scatter: "scatter", psda_freq: "datadisplay", psda_sample: "sampling",
    geo_pyth: "pythag", geo_trig: "trig", geo_circle: "circle", geo_angles: "angles", geo_volume: "volume", geo_triangle: "angles", geo_similar: "similar", geo_arc: "arc", geo_radians: "radians", geo_special: "special",
    alg_literal: "literal", alg_sysineq: "sysineq", adv_poly: "polyops", adv_rational: "rational", psda_spread: "spread", geo_area: "area", geo_polygon: "polygons",
    hard_compose: "composition", hard_circleeq: "circle", hard_perp: "perpendicular", hard_twoway: "twoway", hard_growth: "exponential", hard_quadk: "nonlinear"
  };
  const BY_SKILL = {
    "Words in context": "wic", "Text purpose": "purpose", "Text structure": "purpose", "Cross-text connections": "crosstext",
    "Central ideas": "central", "Inferences": "inference", "Textual evidence": "evidence", "Quantitative evidence": "quant",
    "Rhetorical synthesis": "synthesis", "Transitions": "transitions",
    "Pronouns": "pronoun", "Modifiers": "modifier", "Verb tense": "tense", "Verb forms": "tense", "Punctuation": "punctuation", "Agreement": "agreement", "Boundaries": "boundaries", "Possessives": "possessive"
  };
  function strategyFor(q) {
    if (!q) return "general";
    if (q.gen && BY_GEN[q.gen]) return BY_GEN[q.gen];
    if (q.sk && BY_SKILL[q.sk]) return BY_SKILL[q.sk];
    return "general";
  }
  root.Strategies = { cards: S, strategyFor };
  if (typeof module !== "undefined") module.exports = root.Strategies;
})(typeof window !== "undefined" ? window : globalThis);
