window.FAST_BANK = window.FAST_BANK || {};
FAST_BANK.wdrill = [
  {"id":"wd-001","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nLast summer my family drove to st. augustine to see the old fort.\n\nWhich correction should be made?","o":["Change \"summer\" to \"Summer.\"","Change \"family\" to \"Family.\"","Change \"to see the old fort\" to \"to see The Old Fort.\"","Change \"st. augustine\" to \"St. Augustine.\""],"a":3,"e":"Names of cities are proper nouns, so they need capital letters: **St. Augustine**. Seasons like summer stay lowercase."},
  {"id":"wd-002","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nOn monday, our class will visit the Florida Aquarium.\n\nWhich correction should be made?","o":["Change \"visit\" to \"Visit.\"","Change \"monday\" to \"Monday.\"","Change \"class\" to \"Class.\"","Change \"Aquarium\" to \"aquarium.\""],"a":1,"e":"Days of the week are always capitalized: **Monday**."},
  {"id":"wd-003","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nMy favorite book is called the secret of the hidden lake.\n\nWhich shows the title written correctly?","o":["The Secret of the Hidden Lake","The secret of the hidden lake","The Secret Of The Hidden Lake","the Secret of the Hidden Lake"],"a":0,"e":"In a title, capitalize the first word and the important words. Small words like \"of\" and \"the\" in the middle stay lowercase."},
  {"id":"wd-004","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nWe bought apples bananas and grapes at the farmers market.\n\nWhich correction should be made?","o":["Add a comma after \"bought.\"","Add commas after \"We,\" \"bought,\" and \"grapes.\"","Add commas after \"apples\" and \"bananas.\"","Add a comma after \"We.\""],"a":2,"e":"Use commas to separate three or more items in a list: **apples, bananas, and grapes**."},
  {"id":"wd-005","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nHowever the game was canceled because of lightning.\n\nWhich correction should be made?","o":["Change \"However\" to \"however.\"","Add a comma after \"game.\"","Add a comma after \"canceled.\"","Add a comma after \"However.\""],"a":3,"e":"Use a comma after an introductory word like **However**."},
  {"id":"wd-006","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nYes I would love to come to your dance recital.\n\nWhich correction should be made?","o":["Add a comma after \"Yes.\"","Change \"Yes\" to \"yes.\"","Add a comma after \"come.\"","Add a comma after \"love.\""],"a":0,"e":"Put a comma after words like **Yes**, **No**, and **Well** at the start of a sentence."},
  {"id":"wd-007","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nMy sister was born on June 4 2016 in Tampa Florida.\n\nWhich shows the sentence with correct commas?","o":["My sister was born on June, 4 2016 in Tampa Florida.","My sister was born, on June 4 2016, in Tampa Florida.","My sister was born on June 4, 2016, in Tampa, Florida.","My sister was born on June 4 2016 in Tampa, Florida."],"a":2,"e":"Put a comma between the day and year, and between a city and state. Add one after the year and the state when the sentence keeps going."},
  {"id":"wd-008","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nI wanted to go swimming but the pool was closed.\n\nWhich correction should be made?","o":["Add a comma after \"but.\"","Add a comma after \"swimming.\"","Add a comma after \"pool.\"","Add commas after \"wanted\" and \"go.\""],"a":1,"e":"When **but**, **and**, or **so** joins two complete sentences, put a comma before it."},
  {"id":"wd-009","skill":"w.conv","lv":4,"q":"Read the sentence.\n\n\"Can we bake cookies today asked Lily.\n\nWhich correction should be made?","o":["Add a period after \"Lily.\"","Add a comma after \"Can.\"","Remove the quotation mark before \"Can.\"","Add ?\" after \"today.\""],"a":3,"e":"Lily's exact words need quotation marks at the start AND the end. Her question mark goes inside: **\"Can we bake cookies today?\" asked Lily.**"},
  {"id":"wd-010","skill":"w.conv","lv":4,"q":"Which sentence is written correctly?","o":["\"Let's practice our dance,\" said Maya.","\"Let's practice our dance.\" said Maya.","\"Let's practice our dance\" said Maya.","Let's practice our dance, \"said Maya.\""],"a":0,"e":"When a speaker tag like \"said Maya\" comes after the words, end the quote with a comma inside the quotation marks."},
  {"id":"wd-011","skill":"w.conv","lv":4,"q":"Which sentence is written correctly?","o":["Coach said \"Grab your water bottles.\"","Coach said, \"Grab your water bottles.\"","Coach said, Grab your water bottles.","Coach said, \"grab your water bottles.\""],"a":1,"e":"Put a comma after \"said,\" use quotation marks around the exact words, and capitalize the first word of the quote."},
  {"id":"wd-012","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nThe dogs bone was buried under the orange tree.\n\nWhich correction should be made?","o":["Change \"bone\" to \"bone's.\"","Change \"tree\" to \"tree's.\"","Change \"dogs\" to \"dog's.\"","Change \"dogs\" to \"dogs'.\""],"a":2,"e":"To show that one dog owns the bone, add **'s**: **dog's bone**."},
  {"id":"wd-013","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nThe two girls backpacks were left on the bus.\n\nWhich correction should be made?","o":["Change \"girls\" to \"girls'.\"","Change \"backpacks\" to \"backpack's.\"","Change \"girls\" to \"girl's.\"","Change \"bus\" to \"bus's.\""],"a":0,"e":"For a plural noun that already ends in **s**, add just an apostrophe: **girls'**."},
  {"id":"wd-014","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nMy cousin dont like spicy food.\n\nWhich correction should be made?","o":["Change \"My cousin\" to \"My cousins.\"","Change \"dont\" to \"don't.\"","Change \"dont\" to \"doesn't.\"","Change \"food\" to \"foods.\""],"a":2,"e":"\"My cousin\" is one person, so use **doesn't**, not **don't**. It also needs an apostrophe."},
  {"id":"wd-015","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nThe puppies in the window looks so cute.\n\nWhich correction should be made?","o":["Change \"puppies\" to \"puppy.\"","Change \"cute\" to \"cuter.\"","Change \"window\" to \"windows.\"","Change \"looks\" to \"look.\""],"a":3,"e":"The subject is **puppies** (more than one), so the verb is **look**. Don't be tricked by \"window\" right before the verb."},
  {"id":"wd-016","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nEach of the dancers have a red ribbon.\n\nWhich correction should be made?","o":["Change \"dancers\" to \"dancer.\"","Change \"have\" to \"has.\"","Change \"Each\" to \"All.\"","Change \"ribbon\" to \"ribbons.\""],"a":1,"e":"The subject is **Each**, which means one at a time. One takes **has**."},
  {"id":"wd-017","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nYesterday we go to the beach and build a giant sandcastle.\n\nWhich shows the sentence with the correct verb tense?","o":["Yesterday we went to the beach and built a giant sandcastle.","Yesterday we will go to the beach and build a giant sandcastle.","Yesterday we went to the beach and build a giant sandcastle.","Yesterday we go to the beach and built a giant sandcastle."],"a":0,"e":"\"Yesterday\" tells you it already happened, so both verbs should be in the past: **went** and **built**."},
  {"id":"wd-018","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nMia opened the box and finds a tiny kitten inside.\n\nWhich correction should be made?","o":["Change \"inside\" to \"insides.\"","Change \"finds\" to \"found.\"","Change \"box\" to \"boxes.\"","Change \"opened\" to \"opens.\""],"a":1,"e":"Keep verb tense the same. \"Opened\" is past, so \"finds\" should be **found**."},
  {"id":"wd-019","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nCarlos and Ben forgot his jackets at the park.\n\nWhich correction should be made?","o":["Change \"forgot\" to \"forgets.\"","Change \"park\" to \"Park.\"","Change \"jackets\" to \"jacket.\"","Change \"his\" to \"their.\""],"a":3,"e":"**Carlos and Ben** are two people, so the pronoun should be **their**."},
  {"id":"wd-020","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nThe girls brought there squishy toys to show the class.\n\nWhich correction should be made?","o":["Change \"brought\" to \"bringed.\"","Change \"toys\" to \"toy's.\"","Change \"there\" to \"their.\"","Change \"there\" to \"they're.\""],"a":2,"e":"**Their** shows that something belongs to them. **There** is a place, and **they're** means \"they are.\""},
  {"id":"wd-021","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nTheir going to the science museum on Saturday.\n\nWhich correction should be made?","o":["Change \"Their\" to \"They're.\"","Change \"Saturday\" to \"saturday.\"","Change \"Their\" to \"There.\"","Change \"going\" to \"gone.\""],"a":0,"e":"**They're** is short for \"they are.\" Try it: \"They are going to the museum.\""},
  {"id":"wd-022","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nThe cat licked it's paws after dinner.\n\nWhich correction should be made?","o":["Change \"paws\" to \"paw's.\"","Change \"dinner\" to \"Dinner.\"","Change \"it's\" to \"its.\"","Change \"licked\" to \"licks.\""],"a":2,"e":"**Its** (no apostrophe) shows ownership. **It's** means \"it is.\" The cat licked **its** paws."},
  {"id":"wd-023","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nYour going to love the new dance routine!\n\nWhich correction should be made?","o":["Change \"going\" to \"goes.\"","Change \"Your\" to \"Youre.\"","Change \"routine\" to \"routines.\"","Change \"Your\" to \"You're.\""],"a":3,"e":"**You're** means \"you are.\" Check it: \"You are going to love...\" makes sense."},
  {"id":"wd-024","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nI ate to many cookies at the party.\n\nWhich correction should be made?","o":["Change \"ate\" to \"eight.\"","Change \"to\" to \"too.\"","Change \"many\" to \"much.\"","Change \"to\" to \"two.\""],"a":1,"e":"**Too** means \"more than enough\" or \"also.\" **To** shows direction, and **two** is the number 2."},
  {"id":"wd-025","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nMy brother is taller then me.\n\nWhich correction should be made?","o":["Change \"taller\" to \"tallest.\"","Change \"me\" to \"mine.\"","Change \"then\" to \"than.\"","Change \"is\" to \"are.\""],"a":2,"e":"Use **than** to compare. Use **then** to tell when something happens."},
  {"id":"wd-026","skill":"w.conv","lv":4,"q":"Which group of words is a sentence fragment?","o":["Ava ran all the way across the field to catch the ball.","The ball flew across the field.","We played catch until dark.","Running across the field to catch the ball."],"a":3,"e":"A fragment is missing a part. \"Running across the field...\" doesn't say WHO is running, so it is not a complete sentence."},
  {"id":"wd-027","skill":"w.conv","lv":4,"q":"Which is a run-on sentence?","o":["The manatee swam slowly it ate some sea grass.","The manatee swam slowly. It ate some sea grass.","The manatee swam slowly, and it ate some sea grass.","The manatee swam slowly and ate some sea grass."],"a":0,"e":"A run-on smushes two sentences together without the right punctuation. Fix it with a period, or a comma and \"and.\""},
  {"id":"wd-028","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nWe packed our bags we left for the airport.\n\nWhich is the best way to fix this run-on sentence?","o":["We packed our bags, we then left for the airport.","We packed our bags, and we left for the airport.","We packed our bags and, we left for the airport.","We packed, our bags and we left for the airport."],"a":1,"e":"Join the two complete thoughts with a comma and a joining word like **and**, or split them into two sentences."},
  {"id":"wd-029","skill":"w.conv","lv":4,"q":"Which sentence is complete?","o":["Around the orange blossoms.","Because the bees buzzed.","The busy bees all around the sweet orange blossoms.","The bees buzzed around the orange blossoms."],"a":3,"e":"A complete sentence has a subject (**The bees**) and a verb (**buzzed**) and a complete thought."},
  {"id":"wd-030","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nThe girl ___ won the spelling bee is in my class.\n\nWhich word correctly completes the sentence?","o":["who","what","whose","which"],"a":0,"e":"Use **who** for people. Use **which** for things."},
  {"id":"wd-031","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nThe book ___ I borrowed from the library is about volcanoes.\n\nWhich word correctly completes the sentence?","o":["who","that","whose","whom"],"a":1,"e":"Use **that** or **which** for things. **Who** is for people."},
  {"id":"wd-032","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nThe boy ___ dog ran away put up posters around the neighborhood.\n\nWhich word correctly completes the sentence?","o":["what","which","whose","who's"],"a":2,"e":"**Whose** shows ownership: it's the boy's dog. **Who's** means \"who is.\""},
  {"id":"wd-033","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nRight now, my mom ___ dinner in the kitchen.\n\nWhich verb correctly completes the sentence?","o":["is cooking","will be cooking","was cooking","cooked"],"a":0,"e":"\"Right now\" means it's happening at this moment, so use the present progressive: **is cooking**."},
  {"id":"wd-034","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nWe ___ dinner when the lights went out.\n\nWhich verb correctly completes the sentence?","o":["are eating","will be eating","eat","were eating"],"a":3,"e":"Something was going on in the past when something else happened, so use **were eating** (past progressive)."},
  {"id":"wd-035","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nTomorrow at noon, we ___ to Orlando.\n\nWhich verb correctly completes the sentence?","o":["drived","will be driving","had been driving","are drove"],"a":1,"e":"\"Tomorrow\" means the future, so use **will be driving** (future progressive)."},
  {"id":"wd-036","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nYou ___ wear a helmet when you ride your bike. It is the rule.\n\nWhich word best completes the sentence?","o":["might","could","must","may"],"a":2,"e":"**Must** shows that something is required. It's a rule, so **must** fits best."},
  {"id":"wd-037","skill":"w.conv","lv":4,"q":"Read the sentence.\n\n___ I please borrow your pencil?\n\nWhich word is the most polite way to ask for permission?","o":["May","Should","Will","Must"],"a":0,"e":"Use **may** to politely ask for permission."},
  {"id":"wd-038","skill":"w.conv","lv":4,"q":"Which sentence has a prepositional phrase that tells WHERE?","o":["The turtle was shy.","The turtle hid all day yesterday.","The turtle hid under the log.","The turtle hid quickly."],"a":2,"e":"**Under the log** is a prepositional phrase. It starts with the preposition \"under\" and tells where."},
  {"id":"wd-039","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nLucas put his shoes ___ the bed so he could find them in the morning.\n\nWhich preposition makes the most sense?","o":["during","beside","until","since"],"a":1,"e":"**Beside** tells where the shoes are. **During**, **since**, and **until** are about time."},
  {"id":"wd-040","skill":"w.conv","lv":4,"q":"Which word is spelled correctly?","o":["beatiful","beautifull","beutiful","beautiful"],"a":3,"e":"**Beautiful** comes from \"beauty.\" Change the y to i and add **-ful** (just one l)."},
  {"id":"wd-041","skill":"w.conv","lv":4,"q":"Which word is spelled correctly?","o":["beacause","because","becuase","becaus"],"a":1,"e":"Remember: **be-cause**. It starts with \"be\" and ends with \"cause.\""},
  {"id":"wd-042","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nWe will go to the beach on saturday, july 4.\n\nWhich correction should be made?","o":["Remove the comma after \"saturday\" and before \"july.\"","Change \"We\" to \"we.\"","Change \"the beach\" to \"The Beach.\"","Change \"saturday, july\" to \"Saturday, July.\""],"a":3,"e":"Days of the week and months are proper nouns. Both need capital letters."},
  {"id":"wd-043","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nDr. Kim said, \"brush your teeth twice a day.\"\n\nWhich correction should be made?","o":["Change \"Dr.\" to \"dr.\"","Remove the comma after \"said.\"","Change \"brush\" to \"Brush.\"","Move the period outside the quotation marks."],"a":2,"e":"The first word of a quotation starts with a capital letter: **\"Brush your teeth...\"**"},
  {"id":"wd-044","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nFirst we stretched then we practiced our leaps.\n\nWhich shows the sentence written correctly?","o":["First, we stretched. Then we practiced our leaps.","First we stretched, then, we practiced our leaps.","First we, stretched then we practiced our leaps.","First we stretched then, we practiced. our leaps."],"a":0,"e":"Put a comma after an introductory word like **First**, and split the two complete thoughts into two sentences."},
  {"id":"wd-045","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nThe team play hard every game.\n\nWhich correction should be made?","o":["Change \"hard\" to \"hardly.\"","Change \"play\" to \"plays.\"","Change \"game\" to \"games.\"","Change \"play\" to \"playing.\""],"a":1,"e":"**Team** is one group, so it takes **plays**."},
  {"id":"wd-046","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nSam and his dad goes fishing every Sunday.\n\nWhich correction should be made?","o":["Change \"goes\" to \"going.\"","Change \"Sunday\" to \"sunday.\"","Change \"goes\" to \"go.\"","Change \"his\" to \"their.\""],"a":2,"e":"**Sam and his dad** is two people, so use **go**."},
  {"id":"wd-047","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nThere is three squishy frogs on my shelf.\n\nWhich correction should be made?","o":["Change \"is\" to \"are.\"","Change \"frogs\" to \"frog.\"","Change \"There\" to \"Their.\"","Change \"shelf\" to \"shelves.\""],"a":0,"e":"The subject comes after the verb here: **three frogs**. More than one needs **are**."},
  {"id":"wd-048","skill":"w.conv","lv":4,"q":"Which sentence uses the apostrophe correctly?","o":["The babys' blanket is soft.","The babies's blanket is soft.","The baby,s blanket is soft.","The baby's blanket is soft."],"a":3,"e":"One baby owns the blanket, so add **'s**: **baby's**."},
  {"id":"wd-049","skill":"w.conv","lv":4,"q":"Which sentence is written correctly?","o":["I cant wait for the parade!","I ca'nt wait for the parade!","I cant' wait for the parade!","I can't wait for the parade!"],"a":3,"e":"In a contraction, the apostrophe goes where letters are left out. **Can't** = can + not."},
  {"id":"wd-050","skill":"w.conv","lv":4,"q":"Which sentence is written correctly?","o":["My, dog my cat and my fish all live in our apartment.","My dog, my cat, and my fish all live in our apartment.","My dog my cat, and my fish all live in our apartment.","My dog, my cat and, my fish all live in our apartment."],"a":1,"e":"Put a comma after each item in a list of three or more: **My dog, my cat, and my fish**."},
  {"id":"wd-051","skill":"w.conv","lv":4,"q":"Which sentence uses the correct word?","o":["There are two pelicans on the dock.","They're are two pelicans on the dock.","Their are two pelicans on the dock.","There are too pelicans on the dock."],"a":0,"e":"**There** points to something that exists, and **two** is the number 2."},
  {"id":"wd-052","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nWhen the bell rang the students lined up.\n\nWhich correction should be made?","o":["Add a comma after \"bell.\"","Add a comma after \"When.\"","Add a comma after \"rang.\"","Add a comma after \"students.\""],"a":2,"e":"When a sentence starts with a \"when\" part, put a comma after that part: **When the bell rang,** the students lined up."},
  {"id":"wd-053","skill":"w.conv","lv":4,"q":"Read the sentence.\n\nMy grandmother lives at 22 Palm Street Miami Florida.\n\nWhich correction should be made?","o":["Add a comma after \"lives.\"","Add a comma after \"22.\"","Add commas after \"Street\" and \"Miami.\"","Add commas after \"grandmother\" and \"lives.\""],"a":2,"e":"In an address in a sentence, use commas to separate the street, the city, and the state."},
  {"id":"wd-054","skill":"w.conv","lv":4,"q":"Which word is spelled correctly?","o":["freind","friennd","frend","friend"],"a":3,"e":"**Friend** has \"i before e.\" Tip: you are a friend to the **end** (f-r-i-**end**)."},
  {"id":"wd-055","skill":"w.conv","lv":4,"q":"Which sentence is written correctly?","o":["We ate lunch, and then we went to the museum.","We ate lunch, and, then we went to the museum.","We ate lunch and, then we went to the museum.","We ate, lunch and then we went to the museum."],"a":0,"e":"The comma goes right before **and** when it joins two complete sentences."},
  {"id":"wd-056","skill":"w.conv","lv":5,"q":"Read the sentence.\n\nNeither the coach nor the players was ready for the storm.\n\nWhich correction should be made?","o":["Change \"storm\" to \"storms.\"","Change \"was\" to \"were.\"","Change \"Neither\" to \"Either.\"","Change \"nor\" to \"or.\""],"a":1,"e":"With **neither... nor**, the verb matches the closer subject. \"Players\" is plural, so use **were**."},
  {"id":"wd-057","skill":"w.conv","lv":5,"q":"Read the sentence.\n\nThe scientists, along with their helper, is studying the coral reef.\n\nWhich correction should be made?","o":["Change \"studying\" to \"studied.\"","Change \"is\" to \"are.\"","Change \"their\" to \"his.\"","Remove the comma after \"scientists.\""],"a":1,"e":"The main subject is **The scientists**. The words \"along with their helper\" are extra. Plural subject means **are**."},
  {"id":"wd-058","skill":"w.conv","lv":5,"q":"Read the sentence.\n\nBy the time we arrived, the movie had already started.\n\nWhy does the writer use \"had already started\"?","o":["to show the movie started after we arrived","to show the movie will start soon","to show the movie is starting right now as we arrive","to show the movie started before we arrived"],"a":3,"e":"**Had started** is the past perfect. It shows one past action happened before another past action."},
  {"id":"wd-059","skill":"w.conv","lv":5,"q":"Which sentence is punctuated correctly?","o":["\"Did you see the dolphins?\" asked Jen, \"They were jumping!\"","\"Did you see the dolphins\"? asked Jen. \"They were jumping!\"","\"Did you see the dolphins?\" asked Jen. \"They were jumping!\"","\"Did you see the dolphins,\" asked Jen? \"They were jumping!\""],"a":2,"e":"The question mark goes inside the quotation marks. After \"asked Jen,\" start a new sentence with a period."},
  {"id":"wd-060","skill":"w.conv","lv":5,"q":"Which **two** sentences are written correctly? Choose **two** answers.","o":["The children's paintings, hung in the hallway.","It's going to rain, so bring your umbrella.","The childrens' paintings hung in the hallway.","Its going to rain, so bring your umbrella.","The children's paintings hung in the hallway."],"a":[1,4],"e":"**Children** is already plural, so add **'s**. **It's** means \"it is.\""},
  {"id":"wd-061","skill":"w.org","lv":4,"q":"A student is writing an opinion essay about whether students should have homework on weekends.\n\nWhich sentence would be the best claim for the essay?","o":["Students should not get homework on weekends because they need time to rest and be with family.","My teacher gave us a math worksheet and a reading log last weekend.","Some students get homework on weekends.","Homework can be about math, reading, science, or social studies, and it is often due on Monday morning."],"a":0,"e":"A strong **claim** clearly states the writer's opinion and hints at the reasons. The other choices are just facts."},
  {"id":"wd-062","skill":"w.org","lv":4,"q":"A student is writing an informational essay about how bees help plants.\n\nWhich sentence would be the best controlling idea?","o":["Bees can be yellow and black.","Some people are scared of bees because they can sting.","Bees are my favorite insect because they are fuzzy and buzz loudly.","Bees help plants grow by carrying pollen from flower to flower."],"a":3,"e":"A **controlling idea** tells what the whole essay will explain. This one names the topic and the main point."},
  {"id":"wd-063","skill":"w.org","lv":4,"q":"Read the paragraph.\n\n________. They can sleep up to 22 hours a day. Their leafy diet gives them very little energy, so they rest a lot. Even when awake, they move slowly from branch to branch.\n\nWhich sentence is the best topic sentence for the paragraph?","o":["Koalas spend most of their lives sleeping and resting.","Koalas live in eucalyptus forests in Australia.","I saw a koala sleeping high up in a tree at the zoo once.","Some animals are very fast."],"a":0,"e":"Every detail in the paragraph is about how much koalas sleep and rest. The topic sentence should tell that main idea."},
  {"id":"wd-064","skill":"w.org","lv":4,"q":"Read the sentences.\n\nFlorida gets a lot of rain in the summer. ______, the winter months are usually much drier.\n\nWhich transition best completes the second sentence?","o":["As a result","In addition","In contrast","For example"],"a":2,"e":"Summer is rainy and winter is dry. Those ideas are opposites, so use a contrast transition like **In contrast**."},
  {"id":"wd-065","skill":"w.org","lv":4,"q":"Read the sentences.\n\nManatees need warm water to survive. ______, they gather near warm springs and power plants in the winter.\n\nWhich transition best completes the second sentence?","o":["However","For this reason","Meanwhile","On the other hand"],"a":1,"e":"The second sentence is a result of the first, so a cause-and-effect transition like **For this reason** fits."},
  {"id":"wd-066","skill":"w.org","lv":4,"q":"Read the sentences.\n\nDancing is great exercise. ______, it helps kids make new friends.\n\nWhich transition best completes the second sentence?","o":["Instead","However","Finally","Also"],"a":3,"e":"The writer is adding another reason, so use an adding transition like **Also**."},
  {"id":"wd-067","skill":"w.org","lv":4,"q":"Read the sentences.\n\n1. Next, fold the paper in half again to make a smaller square.\n2. First, start with a square piece of paper.\n3. Finally, unfold the paper to see the crease lines.\n4. Then, fold the paper in half to make a triangle.\n\nWhich is the best order for the sentences?","o":["2, 4, 1, 3","1, 2, 3, 4","4, 2, 1, 3","2, 1, 4, 3"],"a":0,"e":"Look for the signal words: **First**, **Then**, **Next**, **Finally**. They show the order."},
  {"id":"wd-068","skill":"w.org","lv":4,"q":"A student wrote an opinion essay saying that every school should have a garden.\n\nWhich sentence would make the best conclusion?","o":["Gardens need water, sunlight, and good soil to grow vegetables and flowers.","My favorite vegetable is carrots.","A school garden teaches science, healthy eating, and teamwork, so every school should plant one.","Some schools have gardens with vegetables, and some other schools have pretty flower gardens instead."],"a":2,"e":"A strong **conclusion** restates the claim and reminds readers of the reasons."},
  {"id":"wd-069","skill":"w.org","lv":4,"q":"A student is writing an informational essay about hurricanes.\n\nWhich sentence would be the best hook to start the essay?","o":["Hurricanes are a type of storm that forms over the ocean.","Imagine winds so strong they can bend palm trees almost to the ground.","This essay is about hurricanes.","In this essay, I am going to tell you some interesting facts about hurricanes."],"a":1,"e":"A **hook** grabs the reader's attention. \"Imagine...\" makes the reader picture something exciting."},
  {"id":"wd-070","skill":"w.org","lv":4,"q":"Read the paragraph.\n\n(1) Recess helps students focus in class. (2) After running and playing, kids are ready to sit and learn. (3) My cousin has a red bicycle. (4) Teachers say students pay better attention after recess.\n\nWhich sentence does NOT belong in the paragraph?","o":["sentence 1","sentence 2","sentence 3","sentence 4"],"a":2,"e":"The paragraph is about recess helping students focus. A red bicycle has nothing to do with that topic."},
  {"id":"wd-071","skill":"w.org","lv":4,"q":"A student is writing an opinion essay claiming that their class should get a pet fish.\n\nWhich reason best supports the claim?","o":["My neighbor has a dog.","Taking care of a fish would teach us responsibility.","Some fish live in the ocean, and some fish live in lakes.","Fish come in many colors, like orange and blue."],"a":1,"e":"A good **reason** explains WHY the claim is a good idea. Learning responsibility is a strong reason."},
  {"id":"wd-072","skill":"w.org","lv":4,"q":"Read the paragraph.\n\nSea turtles face many dangers. Plastic in the ocean can look like food. ______, bright lights on the beach can confuse baby turtles.\n\nWhich transition best completes the paragraph?","o":["In conclusion","In contrast","For instance","In addition"],"a":3,"e":"The writer is adding another danger, so **In addition** fits best."},
  {"id":"wd-073","skill":"w.org","lv":4,"q":"Read the paragraph.\n\nOrigami is the art of folding paper. ______, people fold paper into cranes, frogs, and boxes.\n\nWhich transition best completes the paragraph?","o":["However","As a result","For example","Finally"],"a":2,"e":"Cranes, frogs, and boxes are examples of origami, so use **For example**."},
  {"id":"wd-074","skill":"w.org","lv":4,"q":"A student's essay has three body paragraphs: one about how dancing builds strength, one about how it improves balance, and one about how it helps kids feel confident.\n\nWhich controlling idea fits all three paragraphs best?","o":["Learning to dance makes kids stronger, steadier, and more confident.","Dancers wear special shoes.","Dancing is a fun hobby.","There are many styles of dance, like tap, ballet, jazz, hip-hop, and salsa."],"a":0,"e":"A good controlling idea covers ALL the body paragraphs: strength, balance, and confidence."},
  {"id":"wd-075","skill":"w.org","lv":4,"q":"Read the sentences.\n\n1. When the storm ended, we helped neighbors clean up branches.\n2. Before the hurricane arrived, we bought water and batteries.\n3. During the storm, we stayed in a room with no windows.\n4. As a result, our street was clear in just one day.\n\nWhich is the best order for the sentences?","o":["2, 3, 1, 4","2, 1, 3, 4","3, 2, 1, 4","1, 2, 3, 4"],"a":0,"e":"Use time clues: **Before**, **During**, **When the storm ended**, and then the result."},
  {"id":"wd-076","skill":"w.org","lv":4,"q":"A student wrote this introduction.\n\nHave you ever seen a bird that can fly backward? Hummingbirds are amazing little birds. ______\n\nWhich sentence best finishes the introduction by stating the controlling idea?","o":["I saw a hummingbird drinking from a flower in my yard last spring.","Birds have feathers.","Their tiny bodies, fast wings, and special diet make them unlike any other bird.","Some people put out red feeders filled with sugar water in their backyards every summer."],"a":2,"e":"The last sentence of an introduction should tell what the essay will explain. This one previews three main points."},
  {"id":"wd-077","skill":"w.org","lv":4,"q":"Read the paragraph.\n\nOur school should have a longer lunch period. ______, many students don't have time to finish eating. Second, a longer lunch would give friends time to talk.\n\nWhich transition best completes the paragraph?","o":["Finally","In contrast","However","First"],"a":3,"e":"The paragraph lists reasons with \"Second,\" so the first reason should start with **First**."},
  {"id":"wd-078","skill":"w.org","lv":4,"q":"A student is writing an opinion essay about why the city should build a new skate park.\n\nWhich sentence would be the best hook?","o":["Skateboards have four wheels.","What if there were a safe, fun place where kids could practice tricks every day?","This essay will tell my opinion about whether we need a skate park.","The city already has several parks with swings, slides, picnic tables, and a pool."],"a":1,"e":"A question that makes readers imagine something is a great **hook**."},
  {"id":"wd-079","skill":"w.org","lv":4,"q":"Read the paragraph.\n\nAlligators are important to the Everglades. They dig holes that fill with water during the dry season. Fish, turtles, and birds use these \"gator holes\" to survive. ______\n\nWhich sentence is the best concluding sentence for the paragraph?","o":["Without alligators, many other animals in the Everglades would struggle.","The Everglades are a large wetland in the southern part of the state of Florida.","Alligators have very strong jaws.","Some people are afraid of alligators because of their sharp teeth."],"a":0,"e":"A **concluding sentence** wraps up the main idea: alligators help other animals."},
  {"id":"wd-080","skill":"w.org","lv":4,"q":"A student wrote this claim: \"Students should be allowed to bring squishy toys to class.\"\n\nWhich reason would a reader find MOST convincing?","o":["Squishy toys are very popular with lots of kids at my school right now.","Squishy toys come in fun shapes like pandas, cats, and food.","Squeezing a small toy can help some students stay calm and focus.","My best friend has fifty squishy toys."],"a":2,"e":"The strongest reason connects to learning. Helping students focus is a reason a teacher would care about."},
  {"id":"wd-081","skill":"w.org","lv":4,"q":"Read the paragraph.\n\nCats and dogs are both popular pets. ______, dogs usually need to go on walks, while cats can stay inside all day.\n\nWhich transition best completes the paragraph?","o":["For example","In addition","Similarly","However"],"a":3,"e":"The sentence shows a difference between cats and dogs, so use a contrast word like **However**."},
  {"id":"wd-082","skill":"w.org","lv":4,"q":"A student is writing an essay explaining how to plant a seed.\n\nWhich way of organizing the essay makes the most sense?","o":["going from the least to the most important opinion","step-by-step order, from first to last","listing problems and solutions","comparing seeds and rocks"],"a":1,"e":"When you explain how to do something, use **sequence** (step-by-step order)."},
  {"id":"wd-083","skill":"w.org","lv":4,"q":"Read the paragraph.\n\n(1) Volunteers cleaned up Clearwater Beach on Saturday. (2) They picked up over 200 pounds of trash. (3) Then they planted sea oats to protect the dunes. (4) Clearwater is a city in Florida with many restaurants.\n\nWhich sentence should be removed because it does not focus on the main idea?","o":["sentence 1","sentence 2","sentence 3","sentence 4"],"a":3,"e":"The paragraph is about the beach cleanup. Sentence 4 is about restaurants, which is off topic."},
  {"id":"wd-084","skill":"w.org","lv":4,"q":"A student wrote an informational essay about how frogs grow from eggs to adults.\n\nWhich sentence would make the best conclusion?","o":["From a tiny egg to a hopping adult, a frog changes in amazing ways as it grows.","Frogs are green.","I really want a pet frog of my own, but my mom says we have no room for one.","Next, the tadpole grows back legs, and a few weeks later it grows its front legs."],"a":0,"e":"The conclusion should sum up the whole topic. This one reminds readers of the whole life cycle."},
  {"id":"wd-085","skill":"w.org","lv":4,"q":"Read the sentences.\n\nThe bake sale raised $300. ______, the class was able to buy new books for the library.\n\nWhich transition best completes the sentences?","o":["On the other hand","Because of this","For example","Before that"],"a":1,"e":"Buying books happened because the sale raised money. **Because of this** shows cause and effect."},
  {"id":"wd-086","skill":"w.org","lv":4,"q":"A student is writing an opinion essay saying that kids should learn to cook.\n\nWhich sentence best states the claim?","o":["Cooking uses pots and pans.","My grandma makes great chicken soup with carrots, celery, and thick noodles every single winter.","Some kids cook with their families, and some kids do not cook at all.","Every kid should learn to cook because it builds healthy habits and important life skills."],"a":3,"e":"The claim clearly says what the writer thinks and why."},
  {"id":"wd-087","skill":"w.org","lv":5,"q":"A student's opinion essay argues that schools should start later in the morning. The student wants to address what someone on the other side might say.\n\nWhich sentence best responds to an opposing view?","o":["Schools across the country start at many different times, and some start as early as 7:00 in the morning on weekdays.","Sleep is important for everyone.","Some people worry a later start means a later dismissal, but most students would gladly trade that for more sleep.","I think school should start later, and I hope you agree with me after reading this."],"a":2,"e":"Strong writers mention the other side (a later dismissal) and then explain why their claim is still better."},
  {"id":"wd-088","skill":"w.org","lv":5,"q":"Read the paragraph.\n\n(1) Some scientists use origami to design space tools. (2) For example, large solar panels can be folded small to fit in a rocket. (3) Once in space, the panels unfold to collect sunlight. (4) Origami is also used in medicine, where tiny folded devices can open inside the body.\n\nWhich sentence would best go at the beginning of this paragraph as a topic sentence?","o":["Paper cranes are my favorite thing to fold.","Rockets are very tall and need lots of fuel to launch.","Origami started hundreds of years ago as a paper-folding art in the country of Japan.","The ancient art of origami is helping scientists solve modern problems."],"a":3,"e":"The paragraph is about how scientists use origami in space AND medicine. The topic sentence should cover both."},
  {"id":"wd-089","skill":"w.org","lv":5,"q":"Read the sentences.\n\nThe ocean water warms up in late summer. ______ the warm water rises, it can fuel thunderstorms that grow into hurricanes.\n\nWhich transition best completes the sentences?","o":["Instead","As","Unless","Although"],"a":1,"e":"**As** shows that one thing happens while and because another happens. It connects the cause (warm water rising) with the effect."},
  {"id":"wd-090","skill":"w.org","lv":5,"q":"A student is writing an essay about why the class should take a field trip to the science center.\n\nWhich **two** sentences would be strong reasons for the essay? Choose **two** answers.","o":["Students can try hands-on experiments that we can't do in our classroom.","The science center has a gift shop.","The center's planetarium show matches our unit on the solar system.","My brother went there last year.","The bus ride would take about an hour."],"a":[0,2],"e":"Strong reasons connect to the purpose of school: hands-on learning and a match with what the class is studying."},
  {"id":"wd-091","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Sleepy Sea Cows\"**\nManatees are large, gentle animals that live in Florida's waters. They cannot survive for long in water colder than about 68 degrees Fahrenheit. In winter, hundreds of manatees swim into warm springs, such as Blue Spring. The spring water stays about 72 degrees all year long.\n\nClaim: Manatees depend on warm springs in the winter.\n\nWhich detail from the source best supports the claim?","o":["Manatees are sometimes called sea cows.","Florida has many kinds of water animals.","In winter, hundreds of manatees swim into warm springs, such as Blue Spring.","Manatees are large, gentle animals that live in Florida's waters."],"a":2,"e":"The best evidence shows manatees going to warm springs in winter, which matches the claim exactly."},
  {"id":"wd-092","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Recess Recharge\"**\nResearchers have studied how breaks affect students. In one study, children who had recess paid more attention in class afterward. They also fidgeted less. Teachers noticed that students seemed calmer after playing outside.\n\nClaim: Recess helps students learn.\n\nWhich detail from the source best supports the claim?","o":["In one study, children who had recess paid more attention in class afterward.","Some schools have recess in the afternoon instead of the morning, right after lunch.","Recess usually happens outside on the playground or the field.","Researchers have studied how breaks affect students."],"a":0,"e":"Paying more attention in class helps learning. That detail connects recess to learning directly."},
  {"id":"wd-093","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Origami in Orbit\"**\nEngineers have used folding patterns inspired by origami to design solar panels for spacecraft. A big panel can fold up into a small package so it fits inside a rocket. Once in space, the panel unfolds to its full size. This lets a spacecraft collect lots of sunlight without taking up much room during launch.\n\nWhich is the best way to cite this source in an essay?","o":["Engineers have used folding patterns to help big solar panels fit inside of rockets, I think.","According to \"Origami in Orbit,\" engineers use folding patterns to help panels fit inside rockets.","\"Origami in Orbit\" is an article I read.","In the article, it says some stuff about space and rockets and how engineers fold big things up so they fit."],"a":1,"e":"A good citation names the source (**\"Origami in Orbit\"**) and then shares the information. \"According to...\" is a great way to start."},
  {"id":"wd-094","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Busy Bees\"**\nHoneybees visit flowers to drink nectar. As they move from flower to flower, pollen sticks to their fuzzy bodies. Some of this pollen rubs off on the next flower, which helps the plant make seeds. Many fruits, such as apples and blueberries, need bees to grow well.\n\nClaim: Bees are important for growing food.\n\nWhich detail best supports the claim?","o":["Honeybees visit flowers to drink nectar.","Bees have fuzzy bodies and six legs.","Many fruits, such as apples and blueberries, need bees to grow well.","Bees can sting if they feel scared or if they think their hive is in danger."],"a":2,"e":"Apples and blueberries are foods. This detail shows bees help food grow."},
  {"id":"wd-095","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Hurricane Ready\"**\nHurricane season in the Atlantic Ocean runs from June 1 to November 30. Experts say families should make a plan before a storm comes. A disaster kit should include water, food that won't spoil, flashlights, batteries, and a first aid kit. Families should also know their evacuation zone.\n\nA student wrote: \"Families should prepare for hurricanes before a storm arrives. For example, they can pack a kit with water, flashlights, and batteries.\"\n\nWhich sentence best explains the evidence?","o":["Having these supplies ready means a family won't have to rush to crowded stores when a storm comes.","My family has a flashlight in the kitchen drawer, and my brother keeps one under his bed too.","Hurricanes have strong winds.","Hurricane season in the Atlantic Ocean runs from June 1 all the way to November 30, which is six months."],"a":0,"e":"Good **elaboration** explains WHY the evidence matters, in your own words. This sentence tells why packing early helps."},
  {"id":"wd-096","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Dance for Your Brain\"**\nDancing is more than exercise. When people dance, they must remember steps and patterns. Scientists have found that learning dance routines can help improve memory. Dancing also improves balance and coordination.\n\nClaim: Dancing is good for the mind, not just the body.\n\nWhich detail best supports the claim?","o":["Dancing also improves balance and coordination.","Dancing is a type of exercise.","People dance at parties, weddings, and festivals in many countries all over the world.","Scientists have found that learning dance routines can help improve memory."],"a":3,"e":"Memory is about the mind. This detail proves dancing helps the brain. Balance is about the body, so it doesn't fit this claim as well."},
  {"id":"wd-097","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Class Pets: A Big Job\"**\nClass pets need care every day, including weekends and holidays. Someone must take the pet home during breaks. Some students are allergic to animal fur. Pets can also get stressed by loud classroom noise.\n\nClaim: Class pets can be hard for schools to care for.\n\nWhich detail best supports the claim?","o":["Hamsters are small, furry, and very fun to watch.","Someone must take the pet home during breaks.","Pets can be many different colors.","Some students love animals of all kinds."],"a":1,"e":"Needing someone to take the pet home is extra work. That shows class pets can be hard to care for."},
  {"id":"wd-098","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Gator Holes\"**\nDuring the dry season in the Everglades, alligators use their snouts and tails to clear out holes. These holes stay filled with water. Fish, turtles, and wading birds come to the holes to drink and find food.\n\nA student wrote: \"Alligators help other animals survive. According to 'Gator Holes,' fish, turtles, and birds use alligator holes to find water and food.\"\n\nWhich sentence best elaborates on the evidence?","o":["Fish and turtles are animals.","Alligators have very sharp teeth and powerful jaws that they use for catching fish, turtles, and birds.","This shows that even a fierce alligator can make the Everglades a better home for others.","The Everglades are a big wetland in southern Florida where many kinds of fish, birds, and reptiles live."],"a":2,"e":"Strong elaboration explains what the evidence MEANS. This sentence connects the detail back to the claim."},
  {"id":"wd-099","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"The Water Cycle\"**\nThe sun heats water in oceans, lakes, and rivers. The water turns into vapor and rises into the sky. High in the sky, the vapor cools and forms clouds. When the clouds get heavy, water falls back to Earth as rain.\n\nWhich is the best way to use information from this source in your own words?","o":["The water cycle is really cool and everyone should learn about it.","Rain is wet.","The sun heats water in oceans, lakes, and rivers. The water turns into vapor and rises into the sky. High in the sky, the vapor cools and forms clouds.","The article \"The Water Cycle\" explains that the sun warms water, which rises, makes clouds, and falls back down as rain."],"a":3,"e":"The best choice **paraphrases** (uses your own words) AND names the source. Copying sentences word for word without quotation marks is not okay."},
  {"id":"wd-100","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Lunch First?\"**\nSome schools have tried having recess before lunch. At these schools, students threw away less food. Kids were not in a hurry to rush outside, so they ate more of their meals. Students also came back to class calmer.\n\nClaim: Schools should have recess before lunch.\n\nWhich **two** details best support the claim? Choose **two** answers.","o":["Students also came back to class calmer.","Some schools have tried having recess before lunch.","At these schools, students threw away less food.","Recess usually lasts about 20 minutes.","Lunch is served in the cafeteria."],"a":[0,2],"e":"Wasting less food and coming back calmer are both good results of recess before lunch, so they support the claim."},
  {"id":"wd-101","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Squeeze and Focus\"**\nSome students have trouble sitting still. Teachers report that small fidget toys can help some students focus. However, other teachers say toys can become distracting if students trade them or toss them around.\n\nClaim: Schools should have rules about fidget toys.\n\nWhich detail best supports the claim?","o":["Other teachers say toys can become distracting if students trade them or toss them around.","Many students like squishy toys.","Fidget toys come in many shapes, sizes, and colors, from poppers to squishy balls and spinners.","Some students have trouble sitting still."],"a":0,"e":"Rules help stop problems. The detail about toys becoming distracting shows why rules are needed."},
  {"id":"wd-102","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Wonderful Wings\"**\nA hummingbird's wings can beat more than 50 times every second. This lets the tiny bird hover in one spot, like a helicopter. It can even fly backward! Hummingbirds need to eat often because flying uses so much energy.\n\nA student wrote: \"Hummingbirds are amazing flyers. Their wings can beat more than 50 times every second.\"\n\nWhich sentence best explains the evidence?","o":["Wings that fast let a hummingbird hover in place and sip nectar without landing.","Hummingbirds live in many places, from gardens to forests to deserts and mountains.","I like hummingbirds because they are tiny and very colorful.","Hummingbirds are very small."],"a":0,"e":"Good elaboration explains why the fact matters. Fast wings let the bird hover, which shows it's an amazing flyer."},
  {"id":"wd-103","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Florida's Springs\"**\nFlorida has more than 1,000 freshwater springs. Water flows up from underground through the rock. Many springs are so clear that you can see fish swimming at the bottom.\n\nWhich sentence correctly cites the source?","o":["Florida has more than 1,000 springs, and I made that up.","Everyone already knows that Florida has lots of springs, so you do not need a source.","\"Florida's Springs\" says that Florida has more than 1,000 freshwater springs.","Springs are underground, says me."],"a":2,"e":"Naming the source title tells readers where the fact came from."},
  {"id":"wd-104","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Ybor City\"**\nYbor City is a neighborhood in Tampa. In the late 1800s, Vicente Martinez Ybor moved his cigar factory there. Workers came from Cuba, Spain, and Italy. Soon the neighborhood was full of factories, bakeries, and social clubs.\n\nClaim: Ybor City grew because of the cigar business.\n\nWhich detail best supports the claim?","o":["Many people visit Tampa today to see its museums, parks, and sandy beaches.","Ybor City is a neighborhood in Tampa.","Tampa is a city in Florida.","Soon the neighborhood was full of factories, bakeries, and social clubs."],"a":3,"e":"The detail shows the neighborhood grew and filled up after the factory came."},
  {"id":"wd-105","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Why Leaves Change\"**\nLeaves are green because of chlorophyll, which helps plants make food from sunlight. In fall, many trees stop making chlorophyll. As the green fades, yellow and orange colors that were there all along begin to show.\n\nClaim: The yellow and orange colors in fall leaves are not new.\n\nWhich detail best supports the claim?","o":["In fall, many trees stop making chlorophyll.","As the green fades, yellow and orange colors that were there all along begin to show.","Chlorophyll is the green coloring that helps plants make their own food from sunlight.","Leaves are green because of chlorophyll."],"a":1,"e":"\"There all along\" proves the colors are not new. They were just hidden by the green."},
  {"id":"wd-106","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Cooking Builds Math Skills\"**\nWhen kids cook, they measure ingredients with cups and spoons. Doubling a recipe means multiplying. Cutting a recipe in half means working with fractions. Cooking also teaches kids to follow steps in order.\n\nA student wrote: \"Cooking helps kids practice math. For example, cutting a recipe in half means working with fractions.\"\n\nWhich sentence best elaborates on this evidence?","o":["Fractions are numbers.","Using fractions in the kitchen helps kids see that math is useful in real life, not just on worksheets.","Recipes have lists of ingredients and numbered steps that tell you what to do first, next, and last.","Some kids like to cook pancakes on Saturday mornings with their parents and then share them with friends."],"a":1,"e":"This sentence explains WHY the evidence matters: it shows math in real life."},
  {"id":"wd-107","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Night Lights and Baby Turtles\"**\nSea turtle hatchlings usually crawl toward the brightest horizon, which is normally the moonlit ocean. Bright lights from buildings can confuse them, and they may crawl the wrong way. Many Florida beach towns ask people to turn off outdoor lights during nesting season.\n\nClaim: Beach lights can be dangerous for baby sea turtles.\n\nWhich detail best supports the claim?","o":["Bright lights from buildings can confuse them, and they may crawl the wrong way.","Many Florida beach towns ask people to turn off outdoor lights during nesting season.","Sea turtle hatchlings crawl to the ocean.","The moon shines on the ocean."],"a":0,"e":"This detail directly shows how lights put turtles in danger by sending them the wrong way."},
  {"id":"wd-108","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Monarch Journey\"**\nEvery fall, millions of monarch butterflies fly south. Some travel more than 2,000 miles to reach forests in Mexico. Scientists are still studying how the butterflies find their way.\n\nWhich sentence uses a direct quotation from the source correctly?","o":["The article says \"Monarch Journey\" that monarchs travel far.","Monarch Journey says monarchs \"fly south and have fun.\"","The article \"Monarch Journey\" says that some monarchs travel more than 2,000 miles to reach forests in Mexico.\"","The article \"Monarch Journey\" says that some monarchs \"travel more than 2,000 miles to reach forests in Mexico.\""],"a":3,"e":"Exact words from a source go inside quotation marks at both ends. Name the source too."},
  {"id":"wd-109","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Why Kids Need Sleep\"**\nDoctors say kids ages 6 to 12 need 9 to 12 hours of sleep each night. Sleep helps the brain store what you learned during the day. Kids who don't get enough sleep may have trouble paying attention.\n\nClaim: Getting enough sleep helps kids do well in school.\n\nWhich **two** details best support the claim? Choose **two** answers.","o":["Doctors say kids need 9 to 12 hours of sleep.","Sleep helps the brain store what you learned during the day.","Kids who don't get enough sleep may have trouble paying attention.","Some kids sleep with a stuffed animal.","Many kids have a bedtime."],"a":[1,2],"e":"Storing learning and paying attention both connect sleep to doing well in school."},
  {"id":"wd-110","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Paper Cranes\"**\nIn Japan, the paper crane is a symbol of hope and peace. An old tradition says that folding one thousand cranes can bring good luck. Today, people around the world fold cranes to send kind wishes to others.\n\nA student wrote: \"Origami cranes are special to many people. According to 'Paper Cranes,' they are a symbol of hope and peace.\"\n\nWhich sentence best elaborates on the evidence?","o":["Cranes are tall birds.","Origami paper comes in many colors and patterns, and some sheets are even shiny like gold or silver foil.","Giving a paper crane shares a wish for good things, so even a small gift can feel meaningful.","Japan is a country in Asia made up of thousands of islands in the Pacific Ocean, and its capital is Tokyo."],"a":2,"e":"Elaboration explains why the evidence matters. This sentence tells why a crane means so much to people."},
  {"id":"wd-111","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"School Gardens\"**\nStudents at schools with gardens often try more vegetables. Gardening teaches science lessons about soil, water, and sunlight. Working in a garden also helps students learn to work as a team.\n\nClaim: School gardens help students learn science.\n\nWhich detail best supports the claim?","o":["Gardening teaches science lessons about soil, water, and sunlight.","Students at schools with gardens often try more vegetables.","Gardens need water.","Working in a garden also helps students learn how to work together as a team."],"a":0,"e":"Soil, water, and sunlight are science topics. This detail matches the claim about science best."},
  {"id":"wd-112","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"The Speedy Cheetah\"**\nThe cheetah is the fastest land animal, faster than any horse or lion. Its spotted coat helps it hide in tall, dry grass. It can reach a top speed of about 70 miles per hour. However, it gets tired quickly and can only keep that speed for a short distance.\n\nA student claims: \"Cheetahs can run fast for a very long time.\"\n\nWhich detail from the source shows that the student's claim is NOT correct?","o":["Its spotted coat helps it hide in tall, dry grass.","The cheetah is the fastest land animal on Earth, faster than any horse or lion.","It can reach a top speed of about 70 miles per hour.","It gets tired quickly and can only keep that speed for a short distance."],"a":3,"e":"The source says cheetahs tire quickly. That proves they can't run fast for a long time. Always check that evidence really matches the claim!"},
  {"id":"wd-113","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Kids in the Kitchen\"**\nCooking at home can be healthier than eating fast food. When kids help cook, they learn what goes into their meals. They also become more willing to try new foods.\n\nWhich sentence correctly paraphrases the source?","o":["Kids should only eat fast food.","Cooking is hard and messy, so kids should leave all of the cooking to the grown-ups at home.","Kids who help cook learn about the ingredients in their food and are more open to new dishes.","When kids help cook, they learn what goes into their meals. They also become more willing to try new foods."],"a":2,"e":"To **paraphrase** is to say the same idea in your own words. The last choice copies the source word for word."},
  {"id":"wd-114","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Lightning Safety\"**\nLightning can strike more than 10 miles away from a storm. Experts say, \"When thunder roars, go indoors.\" People should wait 30 minutes after the last thunder before going back outside.\n\nClaim: People should go inside as soon as they hear thunder.\n\nWhich detail best supports the claim?","o":["Thunder is a loud sound.","Lightning can strike more than 10 miles away from a storm.","Storms can happen in summer.","People should wait 30 minutes after the last thunder before going back outside."],"a":1,"e":"Lightning can strike far from a storm, so even distant thunder means danger. That supports going in right away."},
  {"id":"wd-115","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"The Everglades\"**\nThe Everglades is a huge wetland in southern Florida. It is sometimes called the \"River of Grass\" because a slow, wide sheet of water flows through tall sawgrass. Many animals, including the endangered Florida panther, live there.\n\nWhich is the best way to include information from this source in an essay?","o":["\"It is sometimes called the 'River of Grass' because a slow, wide sheet of water flows through tall sawgrass.\"","I read it somewhere that it is a river of grass.","The Everglades is called the River of Grass, and it is a really cool place to visit with lots of animals.","The article \"The Everglades\" explains that it is called the \"River of Grass\" because water slowly flows through tall sawgrass."],"a":3,"e":"The best choice names the source, uses quotation marks for the special phrase, and explains it."},
  {"id":"wd-116","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Recess Before Lunch: The Other Side\"**\nSome teachers say that recess before lunch is hard to schedule. Students may get very hungry while playing. Other students may come into the cafeteria sweaty and need extra time to wash their hands.\n\nClaim: Recess before lunch can cause problems.\n\nWhich detail best supports the claim?","o":["Some schools have recess twice a day.","Lunch is an important meal for growing kids.","Students may get very hungry while playing.","Teachers plan schedules."],"a":2,"e":"Getting very hungry is a problem caused by playing before eating. This supports the claim."},
  {"id":"wd-117","skill":"w.evid","lv":4,"q":"Read the source.\n\n**\"Moon Phases\"**\nThe moon does not make its own light. We see it because sunlight bounces off its surface. As the moon travels around Earth, we see different amounts of its sunlit side. That is why the moon seems to change shape over about a month.\n\nClaim: The moon only seems to change shape.\n\nWhich detail best supports the claim?","o":["As the moon travels around Earth, we see different amounts of its sunlit side.","The moon does not make its own light.","The moon is very far away from our planet Earth, about 239,000 miles away on average.","People like to look at the full moon."],"a":0,"e":"This detail explains that the moon itself stays the same. We just see different amounts of its lit side, so it only SEEMS to change."},
  {"id":"wd-118","skill":"w.evid","lv":5,"q":"Read the two sources.\n\n**Source 1: \"Pets Teach Responsibility\"**\nStudents who care for a class pet take turns feeding it and cleaning its home. Teachers say this helps students learn responsibility.\n\n**Source 2: \"Pets Need Quiet\"**\nSome small animals, like hamsters, sleep during the day. A noisy classroom can disturb their rest and make them stressed.\n\nA student is writing that classes should think carefully before getting a pet. Which sentence uses BOTH sources best?","o":["According to \"Pets Teach Responsibility,\" students take turns feeding the class pet and cleaning its home every day.","\"Pets Teach Responsibility\" shows pets can teach students to be responsible, but \"Pets Need Quiet\" warns that noisy classrooms can stress some animals.","\"Pets Need Quiet\" says hamsters and some other small animals sleep during the day, so a classroom pet needs a calm, quiet place where nobody will bother it.","Both articles are about animals that live in classrooms and eat food."],"a":1,"e":"The best sentence names both sources and shows how their ideas connect to the student's point."},
  {"id":"wd-119","skill":"w.evid","lv":5,"q":"Read the source.\n\n**\"Rising Waters\"**\nScientists measure sea level along Florida's coast. Their data show that sea level in parts of Florida has risen several inches over the past few decades. Higher water can lead to more flooding during high tides and storms.\n\nA student wrote: \"Rising sea levels are a problem for Florida. According to 'Rising Waters,' sea level in parts of Florida has risen several inches in recent decades.\"\n\nWhich sentence best elaborates on the evidence?","o":["A few inches matters, because higher water lets tides and storms push floods farther into neighborhoods.","Sea level is measured in inches.","Scientists use special tools to measure the ocean at many places along the coast, from Miami to Pensacola.","Florida has many beautiful beaches that visitors from all over the world enjoy, especially in the summer months."],"a":0,"e":"This elaboration explains WHY a few inches is a big deal, connecting the evidence to the problem."},
  {"id":"wd-120","skill":"w.evid","lv":5,"q":"Read the source.\n\n**\"Lighthouse Keepers\"**\nBefore lights were automatic, lighthouse keepers lived at lighthouses. They climbed the stairs each evening to light the lamp and kept it burning all night. They also cleaned the lens so the light would shine far out to sea.\n\nClaim: Lighthouse keepers had demanding jobs.\n\nWhich **two** details best support the claim? Choose **two** answers.","o":["They climbed the stairs each evening to light the lamp and kept it burning all night.","Lighthouses are tall.","Lights shine out to sea.","Before lights were automatic, lighthouse keepers lived at lighthouses.","They also cleaned the lens so the light would shine far out to sea."],"a":[0,4],"e":"Climbing stairs every night, staying up all night, and cleaning the lens all show the job took hard work."}
];

FAST_BANK.prompts = [
  {
    id: "wp01",
    mode: "opinion",
    lv: 4,
    title: "Should students have recess before lunch?",
    sources: [
      {
        title: "Play First, Then Eat",
        text: "At most elementary schools, students eat lunch first and then go outside for recess. But some schools have flipped the schedule. At these schools, students play first and eat second. Many principals who tried the switch say they are glad they did.\n\nOne big reason is food. When recess comes right after lunch, some students gobble a few bites and toss the rest in the trash so they can hurry outside. Researchers who studied schools that moved recess before lunch found that students ate more of their fruits and vegetables and wasted less food. Kids were not rushing, because the fun part of the day was already over.\n\nAnother reason is behavior. Running, jumping, and playing tag use up energy. After recess, students walk into the cafeteria ready to sit down. Some lunchroom workers say the cafeteria is calmer when students have already played. Teachers at these schools also report that students settle into afternoon lessons more quickly, because they have had both exercise and a full meal.\n\nThere is also the problem of tummy aches. Running hard right after eating a big meal can make some kids feel sick. When recess comes first, students can digest their food while they sit in class instead of while they race around the playground.\n\nOf course, every school is different. But for many schools, a simple change in the schedule has led to healthier eating, calmer lunchrooms, and happier kids."
      },
      {
        title: "Why Some Schools Keep Lunch First",
        text: "Moving recess before lunch sounds like an easy idea, but some schools have found that it causes new problems. Before a school makes the switch, there are several things to think about.\n\nFirst, there is hunger. Many students eat breakfast very early, sometimes before seven o'clock. By late morning, their stomachs are growling. If they have to play for twenty minutes before eating, some kids may feel tired, cranky, or even dizzy. For these students, lunch first gives them the energy they need to play.\n\nSecond, there is cleanup. After running around outside, students come in sweaty and with dirty hands. Everyone needs to wash up before eating, and that takes time. At a big school, hundreds of students might need to use the sinks in just a few minutes. That can cut into the time students have to eat.\n\nThird, there is scheduling. Many schools have only one cafeteria and several grades that need to use it. Changing when one class goes to recess can change when every other class eats. Some schools also have teachers or aides who watch recess and also help in the cafeteria. Moving recess can leave one of those places without enough helpers.\n\nFinally, some students like having recess as something to look forward to after lunch. It gives them a break in the long afternoon.\n\nRecess before lunch might work well at some schools, but it is not the right choice for every school. Leaders should think carefully about their own students before changing the schedule."
      }
    ],
    prompt: "Some schools have students go to recess before they eat lunch. Other schools keep lunch first. Should your school have recess before lunch?\n\nWrite an opinion essay that states your opinion on whether students should have recess before lunch. Use information from BOTH sources to support your opinion. Be sure to introduce your opinion, give reasons supported by facts and details from the sources, use transition words, and write a conclusion. Name the sources when you use their information.",
    plan: {
      hook: "Picture this: the lunch bell rings and your friends race to the playground, leaving half their lunch behind...",
      claim: "I believe students (should / should not) have recess before lunch because ____ and ____.",
      reasons: [
        "One reason is that ____. According to \"____,\" ____. This shows that ____.",
        "Another reason is that ____. The article \"____\" explains that ____. This matters because ____."
      ],
      conclusion: "In conclusion, recess (should / should not) come before lunch because ____. If schools ____, students will ____."
    },
    keywords: ["recess", "lunch", "food", "waste", "hungry", "schedule", "calm", "cafeteria", "wash"]
  },
  {
    id: "wp02",
    mode: "opinion",
    lv: 4,
    title: "Should kids learn to dance in PE?",
    sources: [
      {
        title: "Dance Your Way to Fitness",
        text: "When people think of PE class, they often picture kickball, running laps, or shooting hoops. But more and more schools are adding dance to their PE lessons. Supporters say dance is one of the best ways for kids to move.\n\nDance is serious exercise. A fast dance routine gets the heart pumping just like running does. Dancers also build strong legs and a strong core from jumping, turning, and holding poses. Many dance styles, such as ballet and hip-hop, also improve flexibility.\n\nDance trains the brain, too. To learn a routine, dancers must remember a series of steps and match them to the beat of the music. Moving in patterns helps kids practice memory, counting, and coordination all at once. Some teachers say students who dance get better at listening and following directions.\n\nAnother benefit is that dance is for everyone. In some sports, a few strong players get the ball most of the time. In a dance class, every student moves the whole time. Students who don't love team sports may find that dance is the kind of exercise they actually enjoy. Dance can also teach students about other cultures, from Irish step dancing to Mexican folk dance to West African dance.\n\nFinally, dancing is a skill kids can use for life. People dance at weddings, festivals, and family parties. Learning a few steps in PE can help kids feel confident when the music starts. For all these reasons, dance deserves a spot in every school's PE class."
      },
      {
        title: "Keep PE Focused on Sports and Games",
        text: "Dance can be fun, but some parents and teachers think PE class is not the best place for it. They point out that PE time is limited. At many schools, students have PE only a few times a week. Every minute spent learning a dance is a minute not spent on other important skills.\n\nThose skills include throwing, catching, kicking, and running. Experts say children who learn these basic movement skills are more likely to stay active as they grow up, because they feel confident joining games with friends. Team sports also teach kids how to cooperate, take turns, and be good winners and losers.\n\nSome students feel uncomfortable dancing in front of classmates. A shy student who is happy to run laps might feel embarrassed doing a dance routine while others watch. If students feel nervous, they may not participate fully, and the lesson won't help them much.\n\nTeaching dance well also takes special training. Not every PE teacher has studied dance, and schools may not have mirrors, a sound system, or a large open floor. Without the right space and training, dance lessons may not be very good.\n\nPeople who hold this view say kids who love to dance can join a dance club, take lessons after school, or perform in a school show. That way, students who want to dance can, and PE can keep its focus on sports and games that every student needs to learn."
      }
    ],
    prompt: "Some schools teach dance as part of PE class. Others keep PE focused on sports and games. Should kids learn to dance in PE?\n\nWrite an opinion essay that states whether you think dance should be part of PE class. Use information from BOTH sources to support your opinion. Introduce your opinion clearly, support it with reasons and details from the sources, use transitions to connect your ideas, and end with a strong conclusion. Name the sources when you use their information.",
    plan: {
      hook: "Five, six, seven, eight! Imagine your whole PE class moving to the beat...",
      claim: "I think kids (should / should not) learn to dance in PE because ____.",
      reasons: [
        "First, ____. In \"____,\" the author explains that ____. This means ____.",
        "Also, ____. According to \"____,\" ____. This shows ____."
      ],
      conclusion: "To sum up, dance (should / should not) be part of PE because ____. Schools should ____."
    },
    keywords: ["dance", "PE", "exercise", "sports", "coordination", "memory", "shy", "skills", "music", "teacher"]
  },
  {
    id: "wp03",
    mode: "opinion",
    lv: 4,
    title: "Should classrooms have class pets?",
    sources: [
      {
        title: "A Furry Friend for Learning",
        text: "In many classrooms, a fish, hamster, or guinea pig is part of the class. Teachers who keep class pets say these animals teach lessons that are hard to learn from a book.\n\nThe first lesson is responsibility. Students take turns feeding the pet, giving it fresh water, and cleaning its cage or tank. They learn that a living creature depends on them every single day. When students have a job to do, many of them take it very seriously and feel proud when the pet is healthy.\n\nClass pets also make science come alive. Students can watch how an animal eats, sleeps, and grows. They can keep journals of what they observe, measure food, and ask questions. A class with a pet fish might learn about water temperature and how fish breathe through their gills.\n\nMany teachers say a pet helps the classroom feel calm and friendly. Watching fish swim can be relaxing. Some shy students find it easier to talk with classmates when they are talking about the class pet. A pet can give everyone something to care about together.\n\nFinally, a class pet can teach kindness. Students learn to be gentle, speak softly, and think about what the animal needs instead of only what they want. These are good habits to practice with people, too. For teachers who are ready to take on the job, a class pet can be one of the best teachers in the room."
      },
      {
        title: "Think Twice Before Getting a Class Pet",
        text: "A class pet might seem like a fun idea, but animal experts and many teachers say schools should think carefully first. A classroom is not always a good home for an animal.\n\nClassrooms can be loud. Bells ring, chairs scrape, and many people talk at once. Some small animals, such as hamsters, are most active at night and sleep during the day. Being woken up by classroom noise again and again can stress them out. Stressed animals can get sick or may bite.\n\nWeekends and holidays are another problem. A pet still needs food, water, and care when school is closed. Someone has to take it home or come in to check on it. Over a long winter or summer break, finding a caregiver can be hard, and moving the animal back and forth can be stressful for it.\n\nHealth is also important. Some students are allergic to fur or to the bedding used in cages. Health experts warn that some animals, including turtles and other reptiles, can carry germs called salmonella that can make people sick. Students must wash their hands every time they touch the pet or its home.\n\nFinally, pets cost money. Food, bedding, cages, and visits to the veterinarian add up quickly, and teachers often pay out of their own pockets.\n\nStudents can still learn about animals in other ways, such as visiting a nature center, watching a live animal camera online, or caring for classroom plants. These choices teach many of the same lessons without putting an animal in a hard situation."
      }
    ],
    prompt: "Some teachers keep a pet in the classroom, and others decide not to. Should classrooms have class pets?\n\nWrite an opinion essay that states whether you think classrooms should have class pets. Use information from BOTH sources to support your opinion. Clearly state your opinion in the introduction, give reasons with facts and details from the sources, use transitions, and finish with a conclusion. Name the sources when you use their information.",
    plan: {
      hook: "Who is the quietest member of the class? In some rooms, it is a fuzzy hamster named Peanut!",
      claim: "I believe classrooms (should / should not) have class pets because ____ and ____.",
      reasons: [
        "One reason is ____. The article \"____\" says that ____. This shows that ____.",
        "Another reason is ____. According to \"____,\" ____. That is important because ____."
      ],
      conclusion: "In the end, class pets (are / are not) a good idea because ____. Teachers should ____."
    },
    keywords: ["pet", "responsibility", "hamster", "science", "allergic", "weekends", "noise", "stress", "care", "salmonella"]
  },
  {
    id: "wp04",
    mode: "informative",
    lv: 4,
    title: "Why do manatees need warm water?",
    sources: [
      {
        title: "Big Bodies, Little Warmth",
        text: "Florida manatees are large, slow-moving mammals that live in rivers, bays, and coastal waters. Adults are often about 10 feet long and can weigh more than 1,000 pounds. Because of their size and their habit of grazing on sea grass, people sometimes call them \"sea cows.\"\n\nYou might think such a big animal would stay warm easily, but manatees have a problem. Unlike whales and seals, manatees do not have a thick layer of blubber to hold in heat. They also have a slow metabolism. Metabolism is the way a body turns food into energy and heat. A slow metabolism means a manatee's body does not make much heat on its own.\n\nBecause of this, manatees are very sensitive to cold. Scientists say manatees have trouble surviving for long in water that is colder than about 68 degrees Fahrenheit. When manatees stay in cold water too long, they can suffer from something called cold stress. Cold stress can make them weak, cause skin sores, and make it hard for them to fight off sickness. In very cold winters, cold stress can even cause manatees to die.\n\nIn summer, this is not a problem. Florida's waters are warm, and manatees can travel widely, even swimming up the Atlantic coast. But when winter brings cold fronts, manatees must find warm water quickly. Their survival depends on it."
      },
      {
        title: "Winter Hideouts",
        text: "Every winter, as cold fronts sweep across Florida, manatees begin to move. They swim toward places where the water stays warm, and they often gather there in large groups.\n\nOne type of warm-water hideout is a natural spring. Florida has hundreds of springs where water bubbles up from deep underground. The water in many of these springs stays about 72 degrees Fahrenheit all year long, even when the air outside is chilly. At Blue Spring State Park, near the St. Johns River, hundreds of manatees can crowd into the spring run on a cold morning. Visitors can watch them from boardwalks above the clear water.\n\nAnother type of hideout was made by people. Some power plants release warm water into nearby bays as part of the way they work. Manatees discovered that this warm water makes a cozy winter shelter. Near Apollo Beach on Tampa Bay, so many manatees gather by a power plant that a viewing center was built so people can see them.\n\nThese warm places help manatees survive, but there is a catch. Manatees must leave the warm water to find food, because sea grass and other plants do not always grow near springs or power plants. On cold days, they may make short trips to eat and then return to warmth.\n\nTo protect manatees, Florida has set aside special areas where boats must go slowly or stay out during winter. Scientists also work to protect springs and sea grass beds so that manatees will have warm water and enough food in the years ahead."
      }
    ],
    prompt: "Manatees are gentle giants that live in Florida's waters, but they cannot handle the cold.\n\nWrite an informative essay that explains why manatees need warm water and how they find it in the winter. Use information from BOTH sources. Introduce your topic with a clear main idea, develop it with facts, definitions, and details from the sources, use transitions to link your ideas, and end with a conclusion. Name the sources when you use their information.",
    plan: {
      hook: "Imagine being as big as a small car but still shivering in water that feels only a little cool...",
      claim: "Manatees need warm water because ____, so in winter they ____.",
      reasons: [
        "First, manatees ____. According to \"____,\" ____. This means ____.",
        "In winter, manatees find warm water at ____. The article \"____\" explains that ____."
      ],
      conclusion: "Warm water is ____ for manatees. By ____, people can help them survive."
    },
    keywords: ["manatee", "warm", "cold stress", "68 degrees", "blubber", "metabolism", "springs", "power plant", "sea grass", "winter"]
  },
  {
    id: "wp05",
    mode: "informative",
    lv: 4,
    title: "How do hurricanes form, and how can families prepare?",
    sources: [
      {
        title: "Birth of a Hurricane",
        text: "A hurricane is a huge, spinning storm with very strong winds and heavy rain. Hurricanes that reach Florida usually begin far away, over the warm waters of the Atlantic Ocean, the Caribbean Sea, or the Gulf of Mexico.\n\nThe most important ingredient for a hurricane is warm ocean water. Scientists say the water usually needs to be at least about 80 degrees Fahrenheit. Warm water heats the air above it. The warm, moist air rises, and as it rises it cools and forms tall thunderstorm clouds. As more warm air rises, more air rushes in near the ocean's surface to take its place.\n\nBecause Earth is spinning, this moving air begins to turn in a giant circle. If the conditions are right, the thunderstorms group together and begin to spin faster. At first, the system is called a tropical depression. When its winds reach 39 miles per hour, it becomes a tropical storm and gets a name. When its winds reach 74 miles per hour, it is officially a hurricane.\n\nIn the middle of a hurricane is the eye, a calm area where the sky may even be clear. Around the eye is the eyewall, where the strongest winds and heaviest rain are found. When a hurricane moves over land or cooler water, it loses its supply of warm, moist air and begins to weaken.\n\nHurricane season in the Atlantic runs from June 1 to November 30, and storms are most common from August through October."
      },
      {
        title: "Ready Before the Storm",
        text: "Hurricanes can bring strong winds, flooding rain, and rising ocean water called storm surge. Emergency experts say the best time to get ready is before hurricane season even begins.\n\nThe first step is to make a family plan. Families should find out whether they live in an evacuation zone. An evacuation zone is an area that may need to leave when a strong storm is coming, usually because it could flood. Families should decide where they would go, such as a friend's house farther inland or a public shelter, and how they would get there. It is also smart to choose a person outside the area whom everyone can call to check in.\n\nThe second step is to build a disaster supply kit. Experts suggest storing at least one gallon of water per person for each day, for several days. The kit should also have food that won't spoil, a manual can opener, flashlights, extra batteries, a first aid kit, any medicines family members need, and supplies for pets.\n\nThe third step is to protect the home. Some families put up shutters or boards to cover windows. They bring in outdoor items like patio chairs and toys, which strong winds can turn into flying objects.\n\nFinally, families should stay informed. When a storm is coming, they should listen to local news, weather radio, or official alerts. If officials tell people in an area to evacuate, they should leave. Getting ready early helps everyone stay calm and safe when a hurricane heads their way."
      }
    ],
    prompt: "People who live in Florida know that hurricanes can be dangerous.\n\nWrite an informative essay that explains how hurricanes form AND what families can do to prepare for one. Use information from BOTH sources. Introduce your topic, organize your ideas into paragraphs, include facts and details from the sources, use transitions, and provide a conclusion. Name the sources when you use their information.",
    plan: {
      hook: "Did you know that a hurricane's calm center can have a blue sky while terrible winds spin all around it?",
      claim: "Hurricanes form when ____, and families can stay safe by ____.",
      reasons: [
        "A hurricane begins when ____. According to \"____,\" ____. Next, ____.",
        "To prepare, families should ____. The article \"____\" explains that ____."
      ],
      conclusion: "Hurricanes are powerful storms, but by understanding ____ and ____, families can ____."
    },
    keywords: ["hurricane", "warm water", "80 degrees", "rises", "spin", "eye", "74 miles per hour", "evacuation", "kit", "batteries"]
  },
  {
    id: "wp06",
    mode: "opinion",
    lv: 5,
    title: "Should schools have a rule about squishy and fidget toys?",
    sources: [
      {
        title: "Small Toys, Big Distractions",
        text: "Squishy toys, poppers, spinners, and other fidget gadgets have become extremely popular with elementary students. While they can be entertaining, many teachers argue that schools need clear rules about when and how these toys are used.\n\nThe main concern is distraction. A toy that clicks, pops, or spins can draw the attention of not only the student holding it but also everyone sitting nearby. Some researchers have studied what happens when children use fidget spinners during lessons. In at least one study, children who used spinners actually paid less attention and remembered less than when they did not have them. Teachers describe students watching a toy spin instead of watching the board.\n\nAnother problem is that collectible toys can turn into trading cards. Students may bargain, argue over trades, or feel left out if they do not own the newest squishy. When a prized toy goes missing, a whole class can lose time searching for it, and friendships can suffer.\n\nNoise and mess are concerns, too. Some squishy toys can tear and leak their filling. Others are tossed across the room like balls.\n\nTeachers who support rules are not necessarily asking for a complete ban. Instead, many suggest guidelines: toys stay in backpacks unless a teacher approves them, toys must be silent, and they may never be traded during school. Clear rules, they say, protect learning time while still allowing a tool for students who truly benefit from one."
      },
      {
        title: "Fidgets Can Help Some Kids Focus",
        text: "Have you ever tapped your pencil or bounced your knee while concentrating? Many people, including adults, move a little while they think. Some scientists believe small movements can help certain people stay alert, especially those who have difficulty sitting still for long periods.\n\nFor some students, including some who have attention challenges or feel anxious, a quiet fidget tool can be helpful. Squeezing a soft squishy ball or rubbing a smooth stone gives the hands something to do, which may let the mind settle on the lesson. Occupational therapists, who help people with everyday skills, sometimes recommend specific fidget tools for students who need them. In those cases, a fidget is not a toy at all; it is a support, like glasses or a pencil grip.\n\nSupporters also point out that fidgets can calm stress. Before a test or a presentation, squeezing something soft may help a nervous student breathe and relax.\n\nHowever, experts who support fidgets emphasize that the type of tool matters. A silent, simple object that stays in one hand is very different from a spinning toy that grabs everyone's attention. They also note that not every student needs a fidget, and a tool that helps one child may distract another.\n\nFor this reason, many people believe the best approach is flexibility. Rather than banning all fidgets, schools can teach students how to use them responsibly and make sure students who need them can keep them."
      }
    ],
    prompt: "Squishy toys and fidget tools are popular, and schools have different ideas about whether students should use them in class.\n\nWrite an opinion essay that argues whether your school should have a rule about squishy and fidget toys, and what that rule should be. Use information from BOTH sources to support your opinion, and explain why the other side's view is not as strong. Organize your essay with an introduction, body paragraphs, and a conclusion, use transitions, and name the sources when you use their information.",
    plan: {
      hook: "Squeeze, pop, click! In some classrooms, those sounds are everywhere...",
      claim: "I believe schools (should / should not) have a rule about fidget toys because ____.",
      reasons: [
        "One reason is ____. According to \"____,\" ____. This shows ____.",
        "Some people argue that ____. However, \"____\" explains that ____, which means ____."
      ],
      conclusion: "For these reasons, ____. A fair rule would be ____ so that ____."
    },
    keywords: ["fidget", "squishy", "distraction", "focus", "rule", "trading", "silent", "calm", "attention", "therapists"]
  },
  {
    id: "wp07",
    mode: "informative",
    lv: 5,
    title: "How do scientists use origami?",
    sources: [
      {
        title: "Folding for Space",
        text: "Origami is the art of folding paper into shapes, and it has been practiced in Japan for hundreds of years. Most people think of paper cranes or jumping frogs. But in recent decades, engineers and scientists have discovered that the mathematics behind folding can help them solve surprisingly difficult problems, especially in space.\n\nThe challenge is size. Spacecraft often need very large parts, such as solar panels that collect sunlight for power. Yet everything must fit inside a rocket for launch. Engineers need ways to fold big, flat objects into small packages that will open smoothly once they reach space.\n\nA Japanese astrophysicist named Koryo Miura developed a folding pattern, now called the Miura fold, that allows a flat sheet to collapse into a compact bundle and then spread open with a single pull. In 1995, a Japanese space mission tested a solar panel array that used this fold.\n\nOther projects have followed. Robert Lang, a former NASA laser physicist who became a famous origami artist, helped engineers design folding patterns for large space structures, including a giant flower-shaped shade that could someday block starlight so telescopes can photograph faraway planets. The enormous sunshield on the James Webb Space Telescope, about the size of a tennis court, also had to be folded carefully to fit inside its rocket before unfolding in space.\n\nEach of these designs shows the same idea: with clever folding, something huge can begin small."
      },
      {
        title: "Tiny Folds, Big Ideas",
        text: "Origami is helping scientists not only in outer space but also at a much smaller scale, including inside the human body.\n\nIn medicine, researchers have designed devices called stents using origami-style folds. A stent is a small tube that doctors place inside a blood vessel to hold it open. Engineers at the University of Oxford created a stent design that could be folded very small, guided through a blood vessel, and then expanded to its full size in the right spot. Folding allows a device to travel through narrow spaces before it opens up to do its job.\n\nRobotics is another field that borrows from origami. Researchers have built small robots out of flat sheets that fold themselves into three-dimensional shapes when heated. Some can then walk, swim, or carry objects. Because they start flat, these robots can be made quickly and cheaply.\n\nScientists have even folded molecules. In a technique known as DNA origami, researchers use strands of DNA, the molecule that carries genetic instructions, to fold into tiny shapes, such as smiley faces and boxes, far too small to see without powerful microscopes. Scientists hope these tiny structures could one day help deliver medicine to exactly the right cells.\n\nFrom stents to robots to molecules, origami gives scientists a way to think about shape and movement. A craft that began with a single sheet of paper is now inspiring inventions that could improve people's lives."
      }
    ],
    prompt: "Origami is a traditional art of folding paper, but today it is also an important tool for scientists and engineers.\n\nWrite an informative essay that explains how scientists and engineers use ideas from origami and why folding is so useful. Use information from BOTH sources. Introduce your topic with a clear controlling idea, group related information into paragraphs, include facts, definitions, and examples from the sources, use precise vocabulary and transitions, and end with a conclusion. Name the sources when you use their information.",
    plan: {
      hook: "What do a paper crane, a space telescope, and a tiny medical tube have in common? They all fold!",
      claim: "Scientists use origami to ____ because folding lets ____.",
      reasons: [
        "In space, ____. According to \"____,\" ____. This is useful because ____.",
        "Origami also helps on a tiny scale. The article \"____\" explains that ____. For example, ____."
      ],
      conclusion: "Origami shows that ____. In the future, folding may help scientists ____."
    },
    keywords: ["origami", "fold", "Miura", "solar panel", "rocket", "telescope", "stent", "robots", "DNA", "engineers"]
  },
  {
    id: "wp08",
    mode: "informative",
    lv: 4,
    title: "The history of the Castillo de San Marcos",
    sources: [
      {
        title: "A Fort Made of Shells",
        text: "In the city of St. Augustine, on Florida's northeast coast, stands a giant stone fort shaped like a star. It is called the Castillo de San Marcos, which means \"Castle of Saint Mark\" in Spanish. It is the oldest masonry fort in the continental United States. Masonry means it is built of stone.\n\nSpain founded St. Augustine in 1565. For more than a hundred years, the Spanish protected the town with forts made of wood. But wooden forts could rot in the damp weather or burn. After pirates attacked the town in 1668, Spanish leaders decided they needed something much stronger.\n\nIn 1672, workers began building a new fort out of a special stone called coquina. Coquina is made of tiny seashells that have been pressed and cemented together over thousands of years. Workers cut the stone from quarries on nearby Anastasia Island and carried it across the water to the building site. It took more than twenty years to finish the main fort, in 1695.\n\nThe star shape had a purpose. Each corner, called a bastion, stuck out so that soldiers could see and fire along the walls, leaving attackers few places to hide.\n\nToday, visitors can walk across the drawbridge, explore the rooms where soldiers once lived, and look out from the top of the walls at the same bay that Spanish soldiers watched more than three hundred years ago."
      },
      {
        title: "The Fort That Was Never Taken",
        text: "The Castillo de San Marcos was soon put to the test. In 1702, English soldiers from the colony of Carolina marched on St. Augustine. About 1,500 townspeople and soldiers crowded inside the fort for safety. The English surrounded it for nearly two months, but their cannons could not break through the walls. Finally, the English burned the town and left.\n\nWhy were the walls so strong? Many people say it was the coquina. Because the stone is soft and full of tiny spaces, cannonballs tended to sink into it or bounce off rather than shatter the walls. In 1740, English forces led by James Oglethorpe of Georgia attacked again. Once more, the fort held.\n\nAlthough no enemy ever captured the Castillo in battle, it did change hands through peace agreements. Spain gave Florida to Great Britain in 1763, and the British controlled the fort for about twenty years. Florida was returned to Spain in 1784. Then, in 1821, Spain handed Florida to the United States. The Americans renamed it Fort Marion, and the U.S. Army used it for many years, sometimes as a prison.\n\nIn 1924, the fort was named a national monument, and in 1942 its original Spanish name was restored. Today the National Park Service cares for it. Each year, visitors watch costumed rangers fire a cannon and learn how this fort of shells protected a city for centuries."
      }
    ],
    prompt: "The Castillo de San Marcos in St. Augustine is one of Florida's most famous landmarks.\n\nWrite an informative essay that explains the history of the Castillo de San Marcos, including how and why it was built and what happened to it over time. Use information from BOTH sources. Introduce your topic, organize events in a logical order, include facts and details from the sources, use transitions such as \"first,\" \"later,\" and \"today,\" and end with a conclusion. Name the sources when you use their information.",
    plan: {
      hook: "Can a fort made of seashells stop a cannonball? In St. Augustine, one did!",
      claim: "The Castillo de San Marcos is an important Florida landmark because ____.",
      reasons: [
        "The Spanish built the fort because ____. According to \"____,\" ____.",
        "Over time, the fort ____. The article \"____\" explains that ____."
      ],
      conclusion: "For more than 300 years, the Castillo de San Marcos has ____. Today, ____."
    },
    keywords: ["Castillo de San Marcos", "St. Augustine", "Spain", "coquina", "shells", "1672", "fort", "cannon", "1702", "national monument"]
  }
];

FAST_BANK.rubric = [
  {
    domain: "w.org",
    name: "Purpose, Focus & Organization",
    max: 4,
    checks: [
      "I stated my opinion (or main idea) clearly in my introduction.",
      "I started with a hook that makes the reader want to keep reading.",
      "Every paragraph stays on topic and connects back to my opinion or main idea.",
      "Each body paragraph begins with a topic sentence that tells what it is about.",
      "I used transition words (First, Also, For example, However, In conclusion) to link my ideas.",
      "My conclusion restates my opinion or main idea and leaves the reader with a final thought."
    ]
  },
  {
    domain: "w.evid",
    name: "Evidence & Elaboration",
    max: 4,
    checks: [
      "I used facts and details from BOTH sources.",
      "I named the source when I used its information (\"According to the article '…', …\").",
      "Every piece of evidence I chose really supports my opinion or main idea.",
      "After each piece of evidence, I explained what it means in my own words.",
      "I put exact words from a source inside quotation marks, and used my own words everywhere else.",
      "I used strong, precise words (not just \"good,\" \"bad,\" or \"stuff\") and topic words from the sources."
    ]
  },
  {
    domain: "w.conv",
    name: "Conventions",
    max: 2,
    checks: [
      "I started every sentence with a capital letter and capitalized names, places, and titles.",
      "I ended each sentence with the right punctuation and used commas in lists and after introductory words.",
      "My sentences are complete (no fragments or run-ons), and my subjects and verbs agree.",
      "I checked tricky words (their/there/they're, its/it's, to/too/two) and my spelling."
    ]
  }
];
